2023-05-28 02:03:35,899 - INFO - add_to_cart method called
2023-05-28 02:03:35,900 - INFO - checking if table exist!!...
2023-05-28 02:03:35,921 - INFO - session closed
2023-05-28 02:03:35,922 - ERROR - key error list index out of range
2023-05-28 02:03:35,922 - INFO - item not present in cart 
2023-05-28 02:03:35,922 - INFO - checking if table exist!!...
2023-05-28 02:03:35,937 - ERROR - Error: connection issue (pymysql.err.OperationalError) (1054, "Unknown column 'item_id' in 'where clause'")
[SQL: SELECT count from item where item_id='c122';]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-05-28 02:03:36,989 - ERROR - Error: connection issue (pymysql.err.OperationalError) (1054, "Unknown column 'item_id' in 'where clause'")
[SQL: SELECT count from item where item_id='c122';]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-05-28 02:03:38,054 - ERROR - Error: connection issue (pymysql.err.OperationalError) (1054, "Unknown column 'item_id' in 'where clause'")
[SQL: SELECT count from item where item_id='c122';]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-05-28 02:03:39,056 - ERROR - Could not perform database eration after 3 retries
2023-05-28 02:03:39,056 - INFO - Validation time: 0.000 seconds
2023-05-28 02:03:39,056 - INFO - Execution time: 3.156 seconds
2023-05-28 02:03:39,057 - ERROR - Exception on /add_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:07:53,700 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:08:14,338 - INFO - Validation time: 2.147 seconds
2023-05-28 02:08:14,339 - INFO - add_to_cart method called
2023-05-28 02:08:14,339 - INFO - checking if table exist!!...
2023-05-28 02:08:14,410 - INFO - session closed
2023-05-28 02:08:14,410 - ERROR - key error list index out of range
2023-05-28 02:08:14,410 - INFO - item not present in cart 
2023-05-28 02:08:14,410 - INFO - checking if table exist!!...
2023-05-28 02:08:14,824 - INFO - session closed
2023-05-28 02:08:14,825 - INFO - checking if table exist!!...
2023-05-28 02:08:17,636 - INFO - row inserted!..
2023-05-28 02:08:17,660 - INFO - session closed
2023-05-28 02:08:17,660 - INFO - Validation time: 2.148 seconds
2023-05-28 02:08:17,660 - INFO - Execution time: 5.470 seconds
2023-05-28 02:09:39,959 - INFO - Validation time: 0.131 seconds
2023-05-28 02:09:39,970 - INFO - show cart  function triggered!...
2023-05-28 02:09:39,971 - INFO - checking if table exist!!...
2023-05-28 02:09:40,061 - INFO - session closed
2023-05-28 02:09:40,075 - INFO - Validation time: 0.142 seconds
2023-05-28 02:09:40,075 - INFO - Execution time: 0.253 seconds
2023-05-28 02:18:01,611 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:18:20,658 - INFO - Validation time: 2.226 seconds
2023-05-28 02:18:20,672 - INFO - add_to_cart method called
2023-05-28 02:18:20,673 - INFO - checking if table exist!!...
2023-05-28 02:18:21,325 - INFO - session closed
2023-05-28 02:18:21,326 - ERROR - key error list index out of range
2023-05-28 02:18:21,326 - INFO - item not present in cart 
2023-05-28 02:18:21,327 - INFO - checking if table exist!!...
2023-05-28 02:18:21,357 - INFO - session closed
2023-05-28 02:18:21,358 - INFO - checking if table exist!!...
2023-05-28 02:18:21,412 - INFO - row inserted!..
2023-05-28 02:18:21,434 - INFO - session closed
2023-05-28 02:18:21,434 - INFO - Validation time: 2.234 seconds
2023-05-28 02:18:21,434 - INFO - Execution time: 3.005 seconds
2023-05-28 02:19:25,194 - INFO - Validation time: 0.226 seconds
2023-05-28 02:19:25,208 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-05-28 02:19:25,209 - INFO - Validation time: 0.243 seconds
2023-05-28 02:19:25,209 - INFO - Execution time: 0.248 seconds
2023-05-28 02:19:25,218 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:23:12,683 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:23:26,024 - INFO - Validation time: 2.214 seconds
2023-05-28 02:23:26,025 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-05-28 02:23:26,025 - INFO - Validation time: 2.215 seconds
2023-05-28 02:23:26,025 - INFO - Execution time: 2.215 seconds
2023-05-28 02:23:26,026 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:27:22,810 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:27:40,297 - INFO - Validation time: 6.921 seconds
2023-05-28 02:28:20,021 - INFO - Validation time: 0.039 seconds
2023-05-28 02:28:20,043 - INFO - show cart  function triggered!...
2023-05-28 02:28:20,045 - INFO - checking if table exist!!...
2023-05-28 02:28:20,167 - INFO - session closed
2023-05-28 02:28:20,173 - INFO - Validation time: 0.049 seconds
2023-05-28 02:28:20,173 - INFO - Execution time: 0.194 seconds
2023-05-28 02:29:25,204 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:29:42,758 - INFO - Validation time: 2.160 seconds
2023-05-28 02:29:42,763 - INFO - show cart  function triggered!...
2023-05-28 02:29:42,763 - INFO - checking if table exist!!...
2023-05-28 02:29:42,949 - INFO - session closed
2023-05-28 02:29:42,950 - INFO - Validation time: 2.164 seconds
2023-05-28 02:29:42,950 - INFO - Execution time: 2.355 seconds
2023-05-28 02:30:50,353 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:31:02,770 - INFO - Validation time: 2.109 seconds
2023-05-28 02:31:02,772 - INFO - show cart  function triggered!...
2023-05-28 02:31:02,772 - INFO - checking if table exist!!...
2023-05-28 02:31:02,821 - INFO - session closed
2023-05-28 02:31:02,821 - ERROR - An exception occurred:list index out of range
2023-05-28 02:31:02,821 - ERROR - list index out of range
2023-05-28 02:31:02,821 - INFO - Validation time: 2.111 seconds
2023-05-28 02:31:02,821 - INFO - Execution time: 2.160 seconds
2023-05-28 02:31:02,822 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:34:33,110 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:34:46,073 - INFO - Validation time: 2.190 seconds
2023-05-28 02:34:46,076 - INFO - show cart  function triggered!...
2023-05-28 02:34:46,076 - INFO - checking if table exist!!...
2023-05-28 02:34:46,133 - INFO - session closed
2023-05-28 02:34:46,133 - ERROR - An exception occurred:list index out of range
2023-05-28 02:34:46,133 - ERROR - list index out of range
2023-05-28 02:34:46,133 - INFO - Validation time: 2.192 seconds
2023-05-28 02:34:46,133 - INFO - Execution time: 2.250 seconds
2023-05-28 02:34:46,134 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:41:24,775 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:41:40,980 - INFO - Validation time: 2.178 seconds
2023-05-28 02:41:40,985 - INFO - show cart  function triggered!...
2023-05-28 02:41:40,986 - INFO - checking if table exist!!...
2023-05-28 02:41:41,286 - INFO - session closed
2023-05-28 02:41:41,286 - ERROR - An exception occurred:list index out of range
2023-05-28 02:41:41,286 - ERROR - list index out of range
2023-05-28 02:41:41,286 - INFO - Validation time: 2.182 seconds
2023-05-28 02:41:41,287 - INFO - Execution time: 2.486 seconds
2023-05-28 02:41:41,287 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:44:23,215 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:44:37,386 - INFO - Validation time: 2.163 seconds
2023-05-28 02:44:37,390 - INFO - show cart  function triggered!...
2023-05-28 02:44:37,390 - INFO - checking if table exist!!...
2023-05-28 02:44:37,513 - INFO - session closed
2023-05-28 02:44:37,514 - ERROR - An exception occurred:list index out of range
2023-05-28 02:44:37,514 - ERROR - list index out of range
2023-05-28 02:44:37,514 - INFO - Validation time: 2.167 seconds
2023-05-28 02:44:37,514 - INFO - Execution time: 2.294 seconds
2023-05-28 02:44:37,515 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:49:57,934 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:50:21,792 - INFO - Validation time: 2.269 seconds
2023-05-28 02:50:21,810 - INFO - show cart  function triggered!...
2023-05-28 02:50:21,811 - INFO - checking if table exist!!...
2023-05-28 02:50:21,930 - INFO - session closed
2023-05-28 02:50:21,931 - ERROR - An exception occurred:list index out of range
2023-05-28 02:50:21,931 - ERROR - list index out of range
2023-05-28 02:50:21,931 - INFO - Validation time: 2.282 seconds
2023-05-28 02:50:21,931 - INFO - Execution time: 2.414 seconds
2023-05-28 02:50:21,935 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:51:26,027 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:51:46,929 - INFO - Validation time: 2.162 seconds
2023-05-28 02:51:46,934 - INFO - show cart  function triggered!...
2023-05-28 02:51:46,935 - INFO - checking if table exist!!...
2023-05-28 02:51:47,007 - INFO - session closed
2023-05-28 02:51:47,007 - ERROR - An exception occurred:list index out of range
2023-05-28 02:51:47,007 - ERROR - list index out of range
2023-05-28 02:51:47,008 - INFO - Validation time: 2.164 seconds
2023-05-28 02:51:47,008 - INFO - Execution time: 2.241 seconds
2023-05-28 02:51:47,008 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:55:15,329 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:55:25,396 - INFO - Validation time: 2.240 seconds
2023-05-28 02:55:25,397 - INFO - show cart  function triggered!...
2023-05-28 02:55:25,397 - INFO - checking if table exist!!...
2023-05-28 02:55:25,500 - INFO - session closed
2023-05-28 02:55:25,501 - INFO - Validation time: 2.241 seconds
2023-05-28 02:55:25,501 - INFO - Execution time: 2.346 seconds
2023-05-28 02:58:03,423 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:58:16,498 - INFO - Validation time: 2.288 seconds
2023-05-28 02:58:16,507 - INFO - show cart  function triggered!...
2023-05-28 02:58:16,508 - INFO - checking if table exist!!...
2023-05-28 02:58:16,660 - INFO - session closed
2023-05-28 02:58:16,661 - INFO - Validation time: 2.291 seconds
2023-05-28 02:58:16,661 - INFO - Execution time: 2.451 seconds
2023-05-28 03:01:55,377 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:02:08,251 - INFO - Validation time: 2.270 seconds
2023-05-28 03:02:08,265 - INFO - show cart  function triggered!...
2023-05-28 03:02:08,268 - INFO - checking if table exist!!...
2023-05-28 03:02:08,439 - INFO - session closed
2023-05-28 03:02:08,441 - INFO - Validation time: 2.279 seconds
2023-05-28 03:02:08,441 - INFO - Execution time: 2.463 seconds
2023-05-28 03:07:52,346 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:08:15,219 - INFO - Validation time: 2.271 seconds
2023-05-28 03:08:15,228 - INFO - add_to_cart method called
2023-05-28 03:08:15,228 - INFO - checking if table exist!!...
2023-05-28 03:08:15,324 - INFO - session closed
2023-05-28 03:08:15,325 - ERROR - key error list index out of range
2023-05-28 03:08:15,325 - INFO - item not present in cart 
2023-05-28 03:08:15,325 - INFO - checking if table exist!!...
2023-05-28 03:08:15,359 - INFO - session closed
2023-05-28 03:08:15,359 - INFO - checking if table exist!!...
2023-05-28 03:08:15,397 - INFO - row inserted!..
2023-05-28 03:08:15,411 - INFO - session closed
2023-05-28 03:08:15,411 - INFO - Validation time: 2.276 seconds
2023-05-28 03:08:15,411 - INFO - Execution time: 2.465 seconds
2023-05-28 03:08:28,954 - INFO - add_to_cart method called
2023-05-28 03:08:28,957 - INFO - checking if table exist!!...
2023-05-28 03:08:28,999 - INFO - session closed
2023-05-28 03:08:29,000 - ERROR - key error list index out of range
2023-05-28 03:08:29,000 - INFO - item not present in cart 
2023-05-28 03:08:29,000 - INFO - checking if table exist!!...
2023-05-28 03:08:29,016 - INFO - session closed
2023-05-28 03:08:29,017 - INFO - checking if table exist!!...
2023-05-28 03:08:29,030 - INFO - row inserted!..
2023-05-28 03:08:29,220 - INFO - session closed
2023-05-28 03:08:29,221 - INFO - Validation time: 0.002 seconds
2023-05-28 03:08:29,221 - INFO - Execution time: 0.276 seconds
2023-05-28 03:08:46,654 - INFO - show cart  function triggered!...
2023-05-28 03:08:46,659 - INFO - checking if table exist!!...
2023-05-28 03:08:46,777 - INFO - session closed
2023-05-28 03:08:46,779 - ERROR - An exception occurred:list index out of range
2023-05-28 03:08:46,779 - ERROR - list index out of range
2023-05-28 03:08:46,780 - INFO - Validation time: 0.004 seconds
2023-05-28 03:08:46,780 - INFO - Execution time: 0.135 seconds
2023-05-28 03:08:46,789 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 03:17:54,697 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:18:18,645 - INFO - Validation time: 2.414 seconds
2023-05-28 03:18:18,667 - INFO - show cart  function triggered!...
2023-05-28 03:18:18,670 - INFO - checking if table exist!!...
2023-05-28 03:18:18,811 - INFO - query select * from external.tbl_cart1 where session_id='debyan_dsdsfed' and is_active= 1;
2023-05-28 03:18:18,853 - INFO - session closed
2023-05-28 03:18:18,855 - ERROR - An exception occurred:list index out of range
2023-05-28 03:18:18,855 - ERROR - list index out of range
2023-05-28 03:18:18,856 - INFO - Validation time: 2.436 seconds
2023-05-28 03:18:18,856 - INFO - Execution time: 2.636 seconds
2023-05-28 03:18:18,860 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 03:19:41,010 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:19:52,657 - INFO - Validation time: 2.255 seconds
2023-05-28 03:19:52,661 - INFO - show cart  function triggered!...
2023-05-28 03:19:52,661 - INFO - checking if table exist!!...
2023-05-28 03:19:52,712 - INFO - query select * from external.tbl_cart1 where session_id='debyan_dsdsfed' and is_active= 1;
2023-05-28 03:19:52,736 - INFO - session closed
2023-05-28 03:19:52,737 - ERROR - An exception occurred:list index out of range
2023-05-28 03:19:52,737 - ERROR - list index out of range
2023-05-28 03:19:52,737 - INFO - Validation time: 2.256 seconds
2023-05-28 03:19:52,737 - INFO - Execution time: 2.335 seconds
2023-05-28 03:19:52,737 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 03:22:21,662 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:23:01,160 - INFO - Validation time: 2.425 seconds
2023-05-28 03:23:01,197 - INFO - show cart  function triggered!...
2023-05-28 03:23:01,200 - INFO - checking if table exist!!...
2023-05-28 03:23:01,364 - INFO - query select * from external.tbl_cart1 where session_id='debyan_dsdsfed' and is_active= 1;
2023-05-28 03:23:01,420 - INFO - session closed
2023-05-28 03:23:01,431 - INFO - Validation time: 2.447 seconds
2023-05-28 03:23:01,431 - INFO - Execution time: 2.707 seconds
2023-05-28 03:25:44,677 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:26:03,973 - INFO - Validation time: 2.146 seconds
2023-05-28 03:26:03,983 - INFO - show cart  function triggered!...
2023-05-28 03:26:03,983 - INFO - checking if table exist!!...
2023-05-28 03:26:04,032 - INFO - query select * from external.tbl_cart where session_id='debyan_dsdsfed' and is_active= true;
2023-05-28 03:26:04,048 - INFO - session closed
2023-05-28 03:26:04,051 - INFO - Validation time: 2.152 seconds
2023-05-28 03:26:04,051 - INFO - Execution time: 2.228 seconds
2023-05-28 03:29:58,462 - INFO - Validation time: 6.532 seconds
2023-05-28 03:30:49,084 - INFO - Validation time: 0.098 seconds
2023-05-28 03:30:49,098 - INFO - show cart  function triggered!...
2023-05-28 03:30:49,100 - INFO - checking if table exist!!...
2023-05-28 03:30:49,131 - INFO - query select * from external.tbl_cart where session_id='debyan_dsdsfed' and is_active= true;
2023-05-28 03:30:49,145 - INFO - session closed
2023-05-28 03:30:49,149 - INFO - Validation time: 0.109 seconds
2023-05-28 03:30:49,149 - INFO - Execution time: 0.168 seconds
2023-05-28 03:35:07,628 - INFO - Validation time: 2.296 seconds
2023-05-28 03:35:07,644 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-05-28 03:35:07,645 - INFO - Validation time: 2.310 seconds
2023-05-28 03:35:07,645 - INFO - Execution time: 2.320 seconds
2023-05-28 03:35:07,649 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 03:36:31,444 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:36:47,112 - INFO - Validation time: 2.171 seconds
2023-05-28 03:36:47,116 - INFO - add_to_cart method called
2023-05-28 03:36:47,117 - INFO - checking if table exist!!...
2023-05-28 03:36:47,176 - INFO - session closed
2023-05-28 03:36:47,176 - ERROR - key error list index out of range
2023-05-28 03:36:47,176 - INFO - item not present in cart 
2023-05-28 03:36:47,177 - INFO - checking if table exist!!...
2023-05-28 03:36:47,192 - INFO - session closed
2023-05-28 03:36:47,192 - INFO - checking if table exist!!...
2023-05-28 03:36:47,221 - INFO - row inserted!..
2023-05-28 03:36:47,229 - INFO - session closed
2023-05-28 03:36:47,229 - INFO - Validation time: 2.173 seconds
2023-05-28 03:36:47,230 - INFO - Execution time: 2.288 seconds
2023-05-28 03:37:42,368 - INFO - add_to_cart method called
2023-05-28 03:37:42,369 - INFO - checking if table exist!!...
2023-05-28 03:37:42,387 - INFO - session closed
2023-05-28 03:37:42,388 - INFO - item is already present in cart!! updating..
2023-05-28 03:37:42,388 - INFO - checking if table exist!!...
2023-05-28 03:37:42,398 - INFO - session closed
2023-05-28 03:37:42,399 - INFO - checking if table exist!!...
2023-05-28 03:37:42,407 - INFO - row inserted!..
2023-05-28 03:37:42,417 - INFO - session closed
2023-05-28 03:37:42,418 - INFO - Validation time: 0.000 seconds
2023-05-28 03:37:42,418 - INFO - Execution time: 0.052 seconds
2023-05-28 04:37:15,409 - INFO - Validation time: 2.339 seconds
2023-05-28 04:37:15,422 - INFO - add_to_cart method called
2023-05-28 04:37:15,423 - INFO - checking if table exist!!...
2023-05-28 04:37:15,512 - INFO - session closed
2023-05-28 04:37:15,512 - INFO - item is already present in cart!! updating..
2023-05-28 04:37:15,513 - INFO - checking if table exist!!...
2023-05-28 04:37:15,527 - INFO - session closed
2023-05-28 04:37:15,528 - INFO - checking if table exist!!...
2023-05-28 04:37:15,539 - INFO - row inserted!..
2023-05-28 04:37:15,553 - INFO - session closed
2023-05-28 04:37:15,553 - INFO - Validation time: 2.351 seconds
2023-05-28 04:37:15,554 - INFO - Execution time: 2.487 seconds
2023-05-28 04:37:52,142 - INFO - add_to_cart method called
2023-05-28 04:37:52,149 - INFO - checking if table exist!!...
2023-05-28 04:37:52,215 - INFO - session closed
2023-05-28 04:37:52,215 - INFO - item is already present in cart!! updating..
2023-05-28 04:37:52,216 - INFO - checking if table exist!!...
2023-05-28 04:37:52,230 - INFO - session closed
2023-05-28 04:37:52,230 - INFO - checking if table exist!!...
2023-05-28 04:37:52,272 - INFO - row inserted!..
2023-05-28 04:37:52,283 - INFO - session closed
2023-05-28 04:37:52,285 - INFO - Validation time: 0.008 seconds
2023-05-28 04:37:52,285 - INFO - Execution time: 0.164 seconds
2023-05-28 04:38:03,151 - INFO - add_to_cart method called
2023-05-28 04:38:03,151 - INFO - checking if table exist!!...
2023-05-28 04:38:03,187 - INFO - session closed
2023-05-28 04:38:03,188 - INFO - item is already present in cart!! updating..
2023-05-28 04:38:03,188 - INFO - checking if table exist!!...
2023-05-28 04:38:03,208 - INFO - session closed
2023-05-28 04:38:03,208 - INFO - checking if table exist!!...
2023-05-28 04:38:03,225 - INFO - row inserted!..
2023-05-28 04:38:03,249 - INFO - session closed
2023-05-28 04:38:03,249 - INFO - Validation time: 0.000 seconds
2023-05-28 04:38:03,249 - INFO - Execution time: 0.099 seconds
2023-05-29 08:55:42,936 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 08:56:53,371 - INFO - Validation time: 2.455 seconds
2023-05-29 08:56:53,402 - INFO - add_to_cart method called
2023-05-29 08:56:53,406 - INFO - checking if table exist!!...
2023-05-29 08:56:53,840 - INFO - session closed
2023-05-29 08:56:53,844 - ERROR - key error list index out of range
2023-05-29 08:56:53,844 - INFO - item not present in cart 
2023-05-29 08:56:53,845 - INFO - checking if table exist!!...
2023-05-29 08:56:55,028 - INFO - session closed
2023-05-29 08:56:55,028 - INFO - checking if table exist!!...
2023-05-29 08:56:55,090 - INFO - row inserted!..
2023-05-29 08:56:55,106 - INFO - session closed
2023-05-29 08:56:55,106 - INFO - Validation time: 2.482 seconds
2023-05-29 08:56:55,106 - INFO - Execution time: 4.202 seconds
2023-05-29 08:57:11,756 - INFO - add_to_cart method called
2023-05-29 08:57:11,760 - INFO - checking if table exist!!...
2023-05-29 08:57:11,793 - INFO - session closed
2023-05-29 08:57:11,794 - ERROR - key error list index out of range
2023-05-29 08:57:11,794 - INFO - item not present in cart 
2023-05-29 08:57:11,794 - INFO - checking if table exist!!...
2023-05-29 08:57:11,804 - INFO - session closed
2023-05-29 08:57:11,804 - INFO - checking if table exist!!...
2023-05-29 08:57:11,811 - INFO - row inserted!..
2023-05-29 08:57:11,820 - INFO - session closed
2023-05-29 08:57:11,820 - INFO - Validation time: 0.004 seconds
2023-05-29 08:57:11,820 - INFO - Execution time: 0.077 seconds
2023-05-29 08:59:06,142 - INFO - Validation time: 0.327 seconds
2023-05-29 08:59:06,153 - INFO - add_to_cart method called
2023-05-29 08:59:06,155 - INFO - checking if table exist!!...
2023-05-29 08:59:06,234 - INFO - session closed
2023-05-29 08:59:06,235 - ERROR - key error list index out of range
2023-05-29 08:59:06,235 - INFO - item not present in cart 
2023-05-29 08:59:06,235 - INFO - checking if table exist!!...
2023-05-29 08:59:06,251 - INFO - session closed
2023-05-29 08:59:06,252 - INFO - checking if table exist!!...
2023-05-29 08:59:06,261 - INFO - row inserted!..
2023-05-29 08:59:06,273 - INFO - session closed
2023-05-29 08:59:06,273 - INFO - Validation time: 0.341 seconds
2023-05-29 08:59:06,273 - INFO - Execution time: 0.464 seconds
2023-05-29 08:59:40,759 - INFO - show cart  function triggered!...
2023-05-29 08:59:40,768 - INFO - checking if table exist!!...
2023-05-29 08:59:40,841 - INFO - session closed
2023-05-29 08:59:40,868 - INFO - Validation time: 0.003 seconds
2023-05-29 08:59:40,868 - INFO - Execution time: 0.125 seconds
2023-05-29 09:06:41,489 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 09:06:58,397 - INFO - Validation time: 2.383 seconds
2023-05-29 09:06:58,421 - INFO - show cart  function triggered!...
2023-05-29 09:06:58,422 - INFO - checking if table exist!!...
2023-05-29 09:06:58,753 - INFO - session closed
2023-05-29 09:06:58,759 - INFO - Validation time: 2.401 seconds
2023-05-29 09:06:58,759 - INFO - Execution time: 2.753 seconds
2023-05-29 09:09:29,548 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 09:09:41,824 - INFO - Validation time: 2.283 seconds
2023-05-29 09:11:16,413 - INFO - Validation time: 0.165 seconds
2023-05-29 09:11:16,443 - INFO - show cart  function triggered!...
2023-05-29 09:11:16,445 - INFO - checking if table exist!!...
2023-05-29 09:11:16,685 - INFO - session closed
2023-05-29 09:11:16,697 - INFO - Validation time: 0.178 seconds
2023-05-29 09:11:16,698 - INFO - Execution time: 0.452 seconds
2023-05-29 09:15:36,235 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 09:15:47,817 - INFO - Validation time: 2.319 seconds
2023-05-29 09:15:47,831 - INFO - show cart  function triggered!...
2023-05-29 09:15:47,831 - INFO - checking if table exist!!...
2023-05-29 09:15:47,933 - INFO - session closed
2023-05-29 09:15:47,933 - ERROR - An exception occurred:list index out of range
2023-05-29 09:15:47,933 - ERROR - list index out of range
2023-05-29 09:15:47,934 - INFO - Validation time: 2.327 seconds
2023-05-29 09:15:47,934 - INFO - Execution time: 2.437 seconds
2023-05-29 09:15:47,937 - ERROR - Exception on /show_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-29 09:22:25,179 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 09:22:44,001 - INFO - Validation time: 2.307 seconds
2023-05-29 09:26:37,662 - INFO - Validation time: 2.281 seconds
2023-05-29 09:26:37,685 - INFO - show cart  function triggered!...
2023-05-29 09:26:37,687 - INFO - checking if table exist!!...
2023-05-29 09:26:37,856 - INFO - session closed
2023-05-29 09:26:37,860 - INFO - Validation time: 2.289 seconds
2023-05-29 09:26:37,860 - INFO - Execution time: 2.482 seconds
2023-07-17 08:25:14,273 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 08:27:55,988 - INFO - Validation time: 2.166 seconds
2023-07-17 08:27:55,989 - INFO - add_to_cart method called
2023-07-17 08:27:55,990 - INFO - checking if table exist!!...
2023-07-17 08:27:56,303 - INFO - session closed
2023-07-17 08:27:56,304 - ERROR - key error list index out of range
2023-07-17 08:27:56,304 - INFO - item not present in cart 
2023-07-17 08:27:56,304 - INFO - checking if table exist!!...
2023-07-17 08:27:56,317 - INFO - session closed
2023-07-17 08:27:56,317 - INFO - checking if table exist!!...
2023-07-17 08:27:56,359 - INFO - row inserted!..
2023-07-17 08:27:56,378 - INFO - session closed
2023-07-17 08:27:56,378 - INFO - Validation time: 2.167 seconds
2023-07-17 08:27:56,378 - INFO - Execution time: 2.556 seconds
2023-07-17 08:29:55,997 - INFO - Validation time: 0.021 seconds
2023-07-17 08:29:55,997 - INFO - add_to_cart method called
2023-07-17 08:29:55,998 - INFO - checking if table exist!!...
2023-07-17 08:29:56,042 - INFO - session closed
2023-07-17 08:29:56,042 - INFO - item is already present in cart!! updating..
2023-07-17 08:29:56,042 - INFO - checking if table exist!!...
2023-07-17 08:29:56,096 - INFO - session closed
2023-07-17 08:29:56,097 - INFO - checking if table exist!!...
2023-07-17 08:29:56,129 - INFO - row inserted!..
2023-07-17 08:29:56,148 - INFO - session closed
2023-07-17 08:29:56,149 - INFO - Validation time: 0.021 seconds
2023-07-17 08:29:56,149 - INFO - Execution time: 0.172 seconds
2023-07-17 08:36:28,645 - INFO - Validation time: 2.042 seconds
2023-07-17 08:36:28,646 - INFO - show cart  function triggered!...
2023-07-17 08:36:28,647 - INFO - checking if table exist!!...
2023-07-17 08:36:28,671 - INFO - session closed
2023-07-17 08:36:28,672 - INFO - Validation time: 2.043 seconds
2023-07-17 08:36:28,672 - INFO - Execution time: 2.069 seconds
2023-07-17 08:50:55,633 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 08:51:07,657 - INFO - Validation time: 2.096 seconds
2023-07-17 08:51:54,211 - INFO - Validation time: 0.016 seconds
2023-07-17 08:51:54,212 - INFO - show cart  function triggered!...
2023-07-17 08:51:54,212 - INFO - checking if table exist!!...
2023-07-17 08:51:54,302 - INFO - session closed
2023-07-17 08:51:54,303 - ERROR - list indices must be integers or slices, not str
2023-07-17 08:51:54,303 - INFO - Validation time: 0.016 seconds
2023-07-17 08:51:54,303 - INFO - Execution time: 0.109 seconds
2023-07-17 08:51:54,303 - ERROR - Exception on /show_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 08:52:48,366 - INFO - Validation time: 0.017 seconds
2023-07-17 08:54:45,980 - INFO - Validation time: 0.020 seconds
2023-07-17 08:54:45,981 - INFO - show cart  function triggered!...
2023-07-17 08:54:45,981 - INFO - checking if table exist!!...
2023-07-17 08:54:46,000 - INFO - session closed
2023-07-17 08:54:46,001 - ERROR - list indices must be integers or slices, not str
2023-07-17 08:54:46,001 - INFO - Validation time: 0.021 seconds
2023-07-17 08:54:46,001 - INFO - Execution time: 0.041 seconds
2023-07-17 08:54:46,001 - ERROR - Exception on /show_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 08:57:04,357 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 08:57:12,275 - INFO - Validation time: 2.069 seconds
2023-07-17 08:57:12,276 - INFO - show cart  function triggered!...
2023-07-17 08:57:12,276 - INFO - checking if table exist!!...
2023-07-17 08:57:12,357 - INFO - session closed
2023-07-17 08:57:12,357 - ERROR - list indices must be integers or slices, not str
2023-07-17 08:57:12,357 - INFO - Validation time: 2.069 seconds
2023-07-17 08:57:12,357 - INFO - Execution time: 2.151 seconds
2023-07-17 08:57:12,358 - ERROR - Exception on /show_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 08:59:45,661 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 09:00:06,331 - INFO - Validation time: 2.344 seconds
2023-07-17 09:00:06,331 - INFO - show cart  function triggered!...
2023-07-17 09:00:06,332 - INFO - checking if table exist!!...
2023-07-17 09:00:06,406 - INFO - session closed
2023-07-17 09:00:06,406 - ERROR - list indices must be integers or slices, not str
2023-07-17 09:00:06,407 - INFO - Validation time: 2.345 seconds
2023-07-17 09:00:06,407 - INFO - Execution time: 2.421 seconds
2023-07-17 09:00:06,407 - ERROR - Exception on /show_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 09:00:28,794 - INFO - show cart  function triggered!...
2023-07-17 09:00:28,794 - INFO - checking if table exist!!...
2023-07-17 09:00:28,819 - INFO - session closed
2023-07-17 09:00:28,819 - ERROR - list indices must be integers or slices, not str
2023-07-17 09:00:28,819 - INFO - Validation time: 0.000 seconds
2023-07-17 09:00:28,819 - INFO - Execution time: 0.025 seconds
2023-07-17 09:00:28,820 - ERROR - Exception on /show_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 09:01:01,466 - INFO - Validation time: 0.020 seconds
2023-07-17 09:01:27,990 - INFO - Validation time: 0.015 seconds
2023-07-17 09:01:27,990 - INFO - show cart  function triggered!...
2023-07-17 09:01:27,990 - INFO - checking if table exist!!...
2023-07-17 09:01:28,044 - INFO - session closed
2023-07-17 09:01:28,045 - ERROR - list indices must be integers or slices, not str
2023-07-17 09:01:28,045 - INFO - Validation time: 0.016 seconds
2023-07-17 09:01:28,045 - INFO - Execution time: 0.071 seconds
2023-07-17 09:01:28,045 - ERROR - Exception on /show_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 09:02:06,452 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 09:02:17,358 - INFO - Validation time: 2.069 seconds
2023-07-17 09:02:17,359 - INFO - show cart  function triggered!...
2023-07-17 09:02:17,359 - INFO - checking if table exist!!...
2023-07-17 09:02:17,480 - INFO - session closed
2023-07-17 09:02:17,481 - INFO - Validation time: 2.069 seconds
2023-07-17 09:02:17,481 - INFO - Execution time: 2.191 seconds
2023-07-17 09:03:17,139 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 09:03:24,523 - INFO - Validation time: 2.069 seconds
2023-07-17 09:03:24,523 - INFO - show cart  function triggered!...
2023-07-17 09:03:24,524 - INFO - checking if table exist!!...
2023-07-17 09:03:24,637 - INFO - session closed
2023-07-17 09:03:24,638 - INFO - [{'session_id': 'debtest56mou78012testl', 'item_id': '201816_03_01', 'count': 2}]
2023-07-17 09:03:24,638 - INFO - Validation time: 2.069 seconds
2023-07-17 09:03:24,638 - INFO - Execution time: 2.184 seconds
2023-07-17 09:05:12,551 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 09:05:23,780 - INFO - Validation time: 2.052 seconds
2023-07-17 09:06:06,355 - INFO - Validation time: 0.017 seconds
2023-07-17 09:06:06,355 - INFO - {'exp': 1689610538, 'session_id': 'debtest56mou78012testl', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-17 09:06:06,356 - INFO - show cart  function triggered!...
2023-07-17 09:06:06,356 - INFO - checking if table exist!!...
2023-07-17 09:06:06,442 - INFO - session closed
2023-07-17 09:06:06,443 - INFO - [{'session_id': 'debtest56mou78012testl', 'item_id': '201816_03_01', 'count': 2}]
2023-07-17 09:06:06,443 - INFO - Validation time: 0.017 seconds
2023-07-17 09:06:06,443 - INFO - Execution time: 0.105 seconds
2023-07-17 10:35:39,130 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 10:36:54,273 - INFO - Validation time: 2.040 seconds
2023-07-17 10:36:54,273 - INFO - add_to_cart method called
2023-07-17 10:36:54,273 - INFO - checking if table exist!!...
2023-07-17 10:36:54,329 - INFO - session closed
2023-07-17 10:36:54,329 - ERROR - key error list index out of range
2023-07-17 10:36:54,329 - INFO - item not present in cart 
2023-07-17 10:36:54,329 - INFO - checking if table exist!!...
2023-07-17 10:36:54,362 - INFO - session closed
2023-07-17 10:36:54,362 - INFO - checking if table exist!!...
2023-07-17 10:36:54,376 - INFO - row inserted!..
2023-07-17 10:36:54,384 - INFO - session closed
2023-07-17 10:36:54,384 - INFO - Validation time: 2.040 seconds
2023-07-17 10:36:54,384 - INFO - Execution time: 2.150 seconds
2023-07-17 11:09:52,983 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-07-17 11:09:55,940 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 11:10:10,239 - INFO - Validation time: 2.124 seconds
2023-07-17 11:10:10,240 - INFO - add_to_cart method called
2023-07-17 11:10:10,240 - INFO - checking if table exist!!...
2023-07-17 11:10:10,536 - INFO - session closed
2023-07-17 11:10:10,536 - ERROR - key error list index out of range
2023-07-17 11:10:10,536 - INFO - item not present in cart 
2023-07-17 11:10:10,536 - INFO - checking if table exist!!...
2023-07-17 11:10:10,584 - INFO - session closed
2023-07-17 11:10:10,584 - INFO - checking if table exist!!...
2023-07-17 11:10:10,608 - INFO - row inserted!..
2023-07-17 11:10:10,625 - INFO - session closed
2023-07-17 11:10:10,625 - INFO - Validation time: 2.124 seconds
2023-07-17 11:10:10,625 - INFO - Execution time: 2.510 seconds
2023-07-17 11:22:04,332 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 11:22:27,211 - INFO - Validation time: 2.066 seconds
2023-07-17 11:22:27,212 - INFO - add_to_cart method called
2023-07-17 11:22:27,212 - INFO - checking if table exist!!...
2023-07-17 11:22:27,298 - INFO - session closed
2023-07-17 11:22:27,299 - INFO - item is already present in cart!! updating..
2023-07-17 11:22:27,299 - INFO - checking if table exist!!...
2023-07-17 11:22:27,350 - INFO - session closed
2023-07-17 11:22:27,351 - INFO - checking if table exist!!...
2023-07-17 11:22:27,380 - INFO - row inserted!..
2023-07-17 11:22:27,398 - INFO - session closed
2023-07-17 11:22:27,398 - INFO - Validation time: 2.067 seconds
2023-07-17 11:22:27,399 - INFO - Execution time: 2.253 seconds
2023-07-17 11:23:38,436 - INFO - Validation time: 0.022 seconds
2023-07-17 11:23:38,436 - INFO - show cart  function triggered!...
2023-07-17 11:23:38,437 - INFO - checking if table exist!!...
2023-07-17 11:23:38,446 - INFO - query select * from external.tbl_cart where session_id='debtest56mou78012testl' and is_active= true;
2023-07-17 11:23:38,456 - INFO - session closed
2023-07-17 11:23:38,457 - ERROR - An exception occurred:list index out of range
2023-07-17 11:23:38,457 - ERROR - list index out of range
2023-07-17 11:23:38,457 - INFO - Validation time: 0.022 seconds
2023-07-17 11:23:38,457 - INFO - Execution time: 0.043 seconds
2023-07-17 11:23:38,458 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 18:59:47,296 - ERROR - 'session_id'
2023-07-17 18:59:47,306 - ERROR - Exception on /update_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'update_to_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:04:46,887 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:04:55,429 - ERROR - 'session_id'
2023-07-17 19:04:55,429 - ERROR - Exception on /update_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'update_to_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:10:34,211 - INFO - update function triggered!...
2023-07-17 19:10:34,211 - INFO - checking if table exist!!...
2023-07-17 19:10:34,412 - INFO - session closed
2023-07-17 19:10:34,412 - INFO - checking if table exist!!...
2023-07-17 19:10:34,444 - INFO - row inserted!..
2023-07-17 19:10:34,459 - INFO - session closed
2023-07-17 19:11:05,769 - INFO - update function triggered!...
2023-07-17 19:11:05,769 - INFO - checking if table exist!!...
2023-07-17 19:11:05,798 - INFO - session closed
2023-07-17 19:11:05,799 - INFO - checking if table exist!!...
2023-07-17 19:11:05,842 - INFO - row inserted!..
2023-07-17 19:11:05,850 - INFO - session closed
2023-07-17 19:18:13,349 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:21:27,074 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:21:49,496 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-07-17 19:21:49,497 - ERROR - Exception on /remove_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'remove_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:25:07,286 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:25:16,477 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-07-17 19:25:16,478 - ERROR - Exception on /remove_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'remove_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:30:45,550 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-07-17 19:30:45,550 - ERROR - Exception on /remove_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'remove_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:33:57,238 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:34:05,078 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-07-17 19:34:05,078 - ERROR - Exception on /remove_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'remove_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:35:09,862 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:35:16,203 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-07-17 19:35:16,204 - ERROR - Exception on /remove_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'remove_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:36:47,891 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-07-17 19:36:47,891 - ERROR - Exception on /remove_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'remove_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:38:28,908 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:38:36,409 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-07-17 19:38:36,409 - ERROR - Exception on /remove_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'remove_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:41:14,915 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:41:21,269 - INFO - jjjjj
2023-07-17 19:41:21,269 - INFO - remove function triggered!...
2023-07-17 19:41:21,269 - INFO - checking if table exist!!...
2023-07-17 19:41:21,350 - INFO - row inserted!..
2023-07-17 19:41:21,363 - INFO - session closed
2023-07-17 19:41:58,749 - INFO - update function triggered!...
2023-07-17 19:41:58,749 - INFO - checking if table exist!!...
2023-07-17 19:41:58,769 - INFO - session closed
2023-07-17 19:41:58,770 - INFO - checking if table exist!!...
2023-07-17 19:41:58,780 - INFO - row inserted!..
2023-07-17 19:41:58,794 - INFO - session closed
2023-07-17 19:45:11,518 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 19:45:33,940 - INFO - Validation time: 2.106 seconds
2023-07-17 19:45:33,940 - INFO - show cart  function triggered!...
2023-07-17 19:45:33,941 - INFO - checking if table exist!!...
2023-07-17 19:45:33,968 - INFO - query select * from external.tbl_cart where session_id='debtest56mou78012testl' and is_active= true;
2023-07-17 19:45:33,984 - INFO - session closed
2023-07-17 19:45:33,984 - INFO - Validation time: 2.106 seconds
2023-07-17 19:45:33,984 - INFO - Execution time: 2.150 seconds
2023-07-17 19:49:20,258 - INFO - Validation time: 2.049 seconds
2023-07-17 19:49:20,259 - INFO - add_to_cart method called
2023-07-17 19:49:20,259 - INFO - checking if table exist!!...
2023-07-17 19:49:20,270 - INFO - session closed
2023-07-17 19:49:20,270 - ERROR - key error list index out of range
2023-07-17 19:49:20,270 - INFO - item not present in cart 
2023-07-17 19:49:20,270 - INFO - checking if table exist!!...
2023-07-17 19:49:20,295 - INFO - session closed
2023-07-17 19:49:20,295 - ERROR - 'bool' object is not subscriptable
2023-07-17 19:49:20,296 - INFO - Validation time: 2.050 seconds
2023-07-17 19:49:20,296 - INFO - Execution time: 2.087 seconds
2023-07-17 19:49:20,296 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-17 19:49:45,586 - INFO - add_to_cart method called
2023-07-17 19:49:45,586 - INFO - checking if table exist!!...
2023-07-17 19:49:45,610 - INFO - session closed
2023-07-17 19:49:45,610 - INFO - item is already present in cart!! updating..
2023-07-17 19:49:45,610 - INFO - checking if table exist!!...
2023-07-17 19:49:45,619 - INFO - session closed
2023-07-17 19:49:45,620 - INFO - checking if table exist!!...
2023-07-17 19:49:45,626 - INFO - row inserted!..
2023-07-17 19:49:45,635 - INFO - session closed
2023-07-17 19:49:45,635 - INFO - Validation time: 0.000 seconds
2023-07-17 19:49:45,635 - INFO - Execution time: 0.049 seconds
2023-07-17 19:50:41,714 - INFO - Validation time: 0.013 seconds
2023-07-17 19:50:41,714 - INFO - add_to_cart method called
2023-07-17 19:50:41,714 - INFO - checking if table exist!!...
2023-07-17 19:50:41,735 - INFO - session closed
2023-07-17 19:50:41,735 - ERROR - key error list index out of range
2023-07-17 19:50:41,735 - INFO - item not present in cart 
2023-07-17 19:50:41,735 - INFO - checking if table exist!!...
2023-07-17 19:50:41,778 - INFO - session closed
2023-07-17 19:50:41,778 - INFO - checking if table exist!!...
2023-07-17 19:50:41,785 - INFO - row inserted!..
2023-07-17 19:50:41,799 - INFO - session closed
2023-07-17 19:50:41,799 - INFO - Validation time: 0.013 seconds
2023-07-17 19:50:41,799 - INFO - Execution time: 0.098 seconds
2023-07-17 19:50:56,143 - INFO - {'exp': 1689649125, 'session_id': 'debtest56mou78012testl', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-17 19:50:56,143 - INFO - show cart  function triggered!...
2023-07-17 19:50:56,143 - INFO - checking if table exist!!...
2023-07-17 19:50:56,165 - INFO - session closed
2023-07-17 19:50:56,166 - INFO - [{'session_id': 'debtest56mou78012testl', 'item_id': '201816_03_01', 'count': 1}, {'session_id': 'debtest56mou78012testl', 'item_id': '201816_03_02', 'count': 3}]
2023-07-17 19:50:56,166 - INFO - Validation time: 0.000 seconds
2023-07-17 19:50:56,166 - INFO - Execution time: 0.023 seconds
2023-07-17 20:01:55,824 - INFO - Serving on http://0.0.0.0:5008
2023-07-17 20:02:13,709 - INFO - Validation time: 2.067 seconds
2023-07-17 20:03:16,722 - INFO - Validation time: 0.008 seconds
2023-07-17 20:03:16,722 - INFO - {'exp': 1689649959, 'session_id': 'debtest56mou78012testl', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-17 20:03:16,722 - INFO - show cart  function triggered!...
2023-07-17 20:03:16,722 - INFO - checking if table exist!!...
2023-07-17 20:03:16,785 - INFO - session closed
2023-07-17 20:03:16,785 - INFO - [{'session_id': 'debtest56mou78012testl', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl'}, {'session_id': 'debtest56mou78012testl', 'item_id': '201816_03_02', 'count': 3, 'cost': 595.0, 'net_cost': 1785.0, 'cart_id': 'debtest56mou78012testl'}]
2023-07-17 20:03:16,785 - INFO - Validation time: 0.008 seconds
2023-07-17 20:03:16,785 - INFO - Execution time: 0.072 seconds
2023-07-26 09:01:51,994 - INFO - Serving on http://0.0.0.0:5008
2023-07-26 09:02:20,132 - INFO - Validation time: 2.276 seconds
2023-07-26 09:02:20,138 - INFO - {'exp': 1690387848, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-26 09:02:20,147 - INFO - show cart  function triggered!...
2023-07-26 09:02:20,149 - INFO - checking if table exist!!...
2023-07-26 09:02:20,300 - INFO - session closed
2023-07-26 09:02:20,301 - INFO - [{'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}]
2023-07-26 09:02:20,307 - INFO - Validation time: 2.287 seconds
2023-07-26 09:02:20,307 - INFO - Execution time: 2.457 seconds
2023-07-26 09:02:52,935 - INFO - add_to_cart method called
2023-07-26 09:02:52,944 - INFO - checking if table exist!!...
2023-07-26 09:02:53,296 - INFO - session closed
2023-07-26 09:02:53,314 - ERROR - key error list index out of range
2023-07-26 09:02:53,315 - INFO - item not present in cart 
2023-07-26 09:02:53,315 - INFO - checking if table exist!!...
2023-07-26 09:02:53,388 - INFO - session closed
2023-07-26 09:02:53,389 - ERROR - 'bool' object is not subscriptable
2023-07-26 09:02:53,390 - INFO - Validation time: 0.006 seconds
2023-07-26 09:02:53,391 - INFO - Execution time: 0.480 seconds
2023-07-26 09:02:53,401 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-26 09:03:14,799 - INFO - add_to_cart method called
2023-07-26 09:03:14,810 - INFO - checking if table exist!!...
2023-07-26 09:03:14,920 - INFO - session closed
2023-07-26 09:03:14,920 - ERROR - key error list index out of range
2023-07-26 09:03:14,920 - INFO - item not present in cart 
2023-07-26 09:03:14,921 - INFO - checking if table exist!!...
2023-07-26 09:03:14,932 - INFO - session closed
2023-07-26 09:03:14,932 - INFO - checking if table exist!!...
2023-07-26 09:03:14,995 - INFO - row inserted!..
2023-07-26 09:03:15,017 - INFO - session closed
2023-07-26 09:03:15,018 - INFO - Validation time: 0.003 seconds
2023-07-26 09:03:15,018 - INFO - Execution time: 0.238 seconds
2023-07-26 09:03:53,115 - INFO - Validation time: 0.206 seconds
2023-07-26 09:03:53,125 - INFO - {'exp': 1690387848, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-26 09:03:53,132 - INFO - show cart  function triggered!...
2023-07-26 09:03:53,133 - INFO - checking if table exist!!...
2023-07-26 09:03:53,731 - INFO - session closed
2023-07-26 09:03:53,738 - INFO - [{'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}]
2023-07-26 09:03:53,755 - INFO - Validation time: 0.225 seconds
2023-07-26 09:03:53,755 - INFO - Execution time: 0.855 seconds
2023-07-26 09:04:28,249 - INFO - {'exp': 1690387848, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-26 09:04:28,273 - INFO - checkout function triggered!...
2023-07-26 09:04:28,275 - INFO - checking if table exist!!...
2023-07-26 09:04:28,381 - INFO - session closed
2023-07-26 09:04:28,383 - INFO - found cart items
2023-07-26 09:04:28,391 - INFO - checking if table exist!!...
2023-07-26 09:04:28,405 - INFO - session closed
2023-07-26 09:04:28,405 - INFO - checking if table exist!!...
2023-07-26 09:04:28,418 - INFO - session closed
2023-07-26 09:04:28,418 - INFO - checking if table exist!!...
2023-07-26 09:04:28,434 - INFO - session closed
2023-07-26 09:04:28,437 - INFO - checking if table exist!!...
2023-07-26 09:04:29,170 - INFO - session closed
2023-07-26 09:04:29,170 - INFO - checking if table exist!!...
2023-07-26 09:04:29,212 - INFO - session closed
2023-07-26 09:04:29,212 - INFO - no record found with same uid & sessionid . Inserting...
2023-07-26 09:04:29,212 - INFO - checking if table exist!!...
2023-07-26 09:04:29,342 - INFO - row inserted!..
2023-07-26 09:04:29,358 - INFO - session closed
2023-07-26 09:04:29,358 - INFO - {'available_order_no': '00000000-0000-0000-2eea-ece493b5864a-00', 'non_available_order_no': '00000000-0000-0000-2eea-ece493b5864a-01', 'order_id': '00000000-0000-0000-2eea-ece493b5864a', 'available': [{'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}], 'net_total': 8330.0, 'unavailable': [{'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}]}
2023-07-26 09:04:29,365 - INFO - Validation time: 0.007 seconds
2023-07-26 09:04:29,365 - INFO - Execution time: 1.126 seconds
2023-07-26 09:07:03,145 - INFO - Validation time: 2.241 seconds
2023-07-26 09:07:03,153 - INFO - {'exp': 1690387848, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-26 09:07:03,162 - INFO - checkout function triggered!...
2023-07-26 09:07:03,164 - INFO - checking if table exist!!...
2023-07-26 09:07:03,282 - INFO - session closed
2023-07-26 09:07:03,286 - INFO - found cart items
2023-07-26 09:07:03,289 - INFO - checking if table exist!!...
2023-07-26 09:07:03,307 - INFO - session closed
2023-07-26 09:07:03,307 - INFO - checking if table exist!!...
2023-07-26 09:07:03,321 - INFO - session closed
2023-07-26 09:07:03,322 - INFO - checking if table exist!!...
2023-07-26 09:07:03,334 - INFO - session closed
2023-07-26 09:07:03,337 - INFO - checking if table exist!!...
2023-07-26 09:07:03,364 - INFO - session closed
2023-07-26 09:07:03,365 - INFO - checking if table exist!!...
2023-07-26 09:07:03,379 - INFO - session closed
2023-07-26 09:07:03,379 - INFO - checkout table updated..
2023-07-26 09:07:03,380 - INFO - checking if table exist!!...
2023-07-26 09:07:03,402 - INFO - row inserted!..
2023-07-26 09:07:03,418 - INFO - session closed
2023-07-26 09:07:03,418 - INFO - {'available_order_no': '00000000-0000-0000-2eea-ed2cb5788b74-00', 'non_available_order_no': '00000000-0000-0000-2eea-ed2cb5788b74-01', 'order_id': '00000000-0000-0000-2eea-ed2cb5788b74', 'available': [{'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}], 'net_total': 8330.0, 'unavailable': [{'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}]}
2023-07-26 09:07:03,424 - INFO - Validation time: 2.250 seconds
2023-07-26 09:07:03,424 - INFO - Execution time: 2.522 seconds
2023-07-26 09:07:25,505 - INFO - {'exp': 1690387848, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-26 09:07:25,511 - INFO - checkout function triggered!...
2023-07-26 09:07:25,512 - INFO - checking if table exist!!...
2023-07-26 09:07:25,549 - INFO - session closed
2023-07-26 09:07:25,550 - INFO - found cart items
2023-07-26 09:07:25,551 - INFO - checking if table exist!!...
2023-07-26 09:07:25,569 - INFO - session closed
2023-07-26 09:07:25,569 - INFO - checking if table exist!!...
2023-07-26 09:07:25,634 - INFO - session closed
2023-07-26 09:07:25,635 - INFO - checking if table exist!!...
2023-07-26 09:07:25,688 - INFO - session closed
2023-07-26 09:07:25,690 - INFO - checking if table exist!!...
2023-07-26 09:07:25,707 - INFO - session closed
2023-07-26 09:07:25,708 - INFO - checking if table exist!!...
2023-07-26 09:07:25,724 - INFO - session closed
2023-07-26 09:07:25,724 - INFO - checkout table updated..
2023-07-26 09:07:25,725 - INFO - checking if table exist!!...
2023-07-26 09:07:25,738 - INFO - row inserted!..
2023-07-26 09:07:25,758 - INFO - session closed
2023-07-26 09:07:25,758 - INFO - {'available_order_no': '00000000-0000-0000-2eea-ed371380e536-00', 'non_available_order_no': '00000000-0000-0000-2eea-ed371380e536-01', 'order_id': '00000000-0000-0000-2eea-ed371380e536', 'available': [{'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}], 'net_total': 8330.0, 'unavailable': [{'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}]}
2023-07-26 09:07:25,760 - INFO - Validation time: 0.000 seconds
2023-07-26 09:07:25,761 - INFO - Execution time: 0.256 seconds
2023-07-26 09:10:23,775 - INFO - Validation time: 2.238 seconds
2023-07-26 09:10:23,785 - INFO - {'exp': 1690387848, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-26 09:10:23,793 - INFO - checkout function triggered!...
2023-07-26 09:10:23,794 - INFO - checking if table exist!!...
2023-07-26 09:10:23,888 - INFO - session closed
2023-07-26 09:10:23,890 - INFO - found cart items
2023-07-26 09:10:23,892 - INFO - checking if table exist!!...
2023-07-26 09:10:23,925 - INFO - session closed
2023-07-26 09:10:23,926 - INFO - checking if table exist!!...
2023-07-26 09:10:23,949 - INFO - session closed
2023-07-26 09:10:23,950 - INFO - checking if table exist!!...
2023-07-26 09:10:23,962 - INFO - session closed
2023-07-26 09:10:23,965 - INFO - checking if table exist!!...
2023-07-26 09:10:23,980 - INFO - session closed
2023-07-26 09:10:23,980 - INFO - checking if table exist!!...
2023-07-26 09:10:23,994 - INFO - session closed
2023-07-26 09:10:23,995 - INFO - checkout table updated..
2023-07-26 09:10:23,995 - INFO - checking if table exist!!...
2023-07-26 09:10:24,009 - INFO - row inserted!..
2023-07-26 09:10:24,024 - INFO - session closed
2023-07-26 09:10:24,024 - INFO - {'available_order_no': '00000000-0000-0000-2eea-ed8a1f400c48-00', 'non_available_order_no': '00000000-0000-0000-2eea-ed8a1f400c48-01', 'order_id': '00000000-0000-0000-2eea-ed8a1f400c48', 'available': [{'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}], 'net_total': 8330.0, 'unavailable': [{'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}]}
2023-07-26 09:10:24,029 - INFO - Validation time: 2.252 seconds
2023-07-26 09:10:24,029 - INFO - Execution time: 2.496 seconds
2023-07-26 09:10:36,753 - INFO - add_to_cart method called
2023-07-26 09:10:36,757 - INFO - checking if table exist!!...
2023-07-26 09:10:36,829 - INFO - session closed
2023-07-26 09:10:36,830 - INFO - item is already present in cart!! updating..
2023-07-26 09:10:36,831 - INFO - checking if table exist!!...
2023-07-26 09:10:36,884 - INFO - session closed
2023-07-26 09:10:36,886 - INFO - checking if table exist!!...
2023-07-26 09:10:38,409 - INFO - row inserted!..
2023-07-26 09:10:38,422 - INFO - session closed
2023-07-26 09:10:38,422 - INFO - Validation time: 0.001 seconds
2023-07-26 09:10:38,422 - INFO - Execution time: 1.675 seconds
2023-07-26 09:10:45,696 - INFO - add_to_cart method called
2023-07-26 09:10:45,696 - INFO - checking if table exist!!...
2023-07-26 09:10:45,706 - INFO - session closed
2023-07-26 09:10:45,706 - INFO - item is already present in cart!! updating..
2023-07-26 09:10:45,707 - INFO - checking if table exist!!...
2023-07-26 09:10:45,716 - INFO - session closed
2023-07-26 09:10:45,716 - INFO - checking if table exist!!...
2023-07-26 09:10:45,724 - INFO - row inserted!..
2023-07-26 09:10:45,738 - INFO - session closed
2023-07-26 09:10:45,738 - INFO - Validation time: 0.000 seconds
2023-07-26 09:10:45,738 - INFO - Execution time: 0.042 seconds
2023-07-26 09:10:51,577 - INFO - add_to_cart method called
2023-07-26 09:10:51,577 - INFO - checking if table exist!!...
2023-07-26 09:10:51,620 - INFO - session closed
2023-07-26 09:10:51,621 - INFO - item is already present in cart!! updating..
2023-07-26 09:10:51,621 - INFO - checking if table exist!!...
2023-07-26 09:10:51,662 - INFO - session closed
2023-07-26 09:10:51,662 - INFO - checking if table exist!!...
2023-07-26 09:10:51,670 - INFO - row inserted!..
2023-07-26 09:10:51,677 - INFO - session closed
2023-07-26 09:10:51,677 - INFO - Validation time: 0.000 seconds
2023-07-26 09:10:51,677 - INFO - Execution time: 0.100 seconds
2023-07-26 09:10:57,300 - INFO - add_to_cart method called
2023-07-26 09:10:57,300 - INFO - checking if table exist!!...
2023-07-26 09:10:57,311 - INFO - session closed
2023-07-26 09:10:57,312 - INFO - item is already present in cart!! updating..
2023-07-26 09:10:57,312 - INFO - checking if table exist!!...
2023-07-26 09:10:57,322 - INFO - session closed
2023-07-26 09:10:57,322 - INFO - checking if table exist!!...
2023-07-26 09:10:57,329 - INFO - row inserted!..
2023-07-26 09:10:57,338 - INFO - session closed
2023-07-26 09:10:57,338 - INFO - Validation time: 0.000 seconds
2023-07-26 09:10:57,338 - INFO - Execution time: 0.039 seconds
2023-07-26 09:11:09,259 - INFO - {'exp': 1690387848, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-26 09:11:09,263 - INFO - checkout function triggered!...
2023-07-26 09:11:09,264 - INFO - checking if table exist!!...
2023-07-26 09:11:09,315 - INFO - session closed
2023-07-26 09:11:09,319 - INFO - found cart items
2023-07-26 09:11:09,322 - INFO - checking if table exist!!...
2023-07-26 09:11:09,347 - INFO - session closed
2023-07-26 09:11:09,347 - INFO - checking if table exist!!...
2023-07-26 09:11:09,356 - INFO - session closed
2023-07-26 09:11:09,356 - INFO - checking if table exist!!...
2023-07-26 09:11:09,363 - INFO - session closed
2023-07-26 09:11:09,366 - INFO - checking if table exist!!...
2023-07-26 09:11:09,374 - INFO - session closed
2023-07-26 09:11:09,375 - INFO - checking if table exist!!...
2023-07-26 09:11:09,382 - INFO - session closed
2023-07-26 09:11:09,382 - INFO - checkout table updated..
2023-07-26 09:11:09,383 - INFO - checking if table exist!!...
2023-07-26 09:11:09,406 - INFO - row inserted!..
2023-07-26 09:11:09,413 - INFO - session closed
2023-07-26 09:11:09,413 - INFO - {'available_order_no': '00000000-0000-0000-2eea-ed9f46d03ad4-00', 'non_available_order_no': '00000000-0000-0000-2eea-ed9f46d03ad4-01', 'order_id': '00000000-0000-0000-2eea-ed9f46d03ad4', 'available': [{'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_01', 'count': 5, 'cost': 595.0, 'net_cost': 2975.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}], 'net_total': 10710.0, 'unavailable': [{'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}]}
2023-07-26 09:11:09,419 - INFO - Validation time: 0.000 seconds
2023-07-26 09:11:09,419 - INFO - Execution time: 0.161 seconds
2023-07-26 09:12:45,373 - INFO - Validation time: 0.234 seconds
2023-07-26 09:19:46,719 - INFO - Validation time: 2.431 seconds
2023-07-26 09:20:57,833 - INFO - Validation time: 0.308 seconds
2023-07-26 09:20:57,844 - INFO - {'exp': 1690389013, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-26 09:20:57,857 - INFO - show cart  function triggered!...
2023-07-26 09:20:57,859 - INFO - checking if table exist!!...
2023-07-26 09:20:57,943 - INFO - session closed
2023-07-26 09:20:57,947 - INFO - [{'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_01', 'count': 5, 'cost': 595.0, 'net_cost': 2975.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}]
2023-07-26 09:20:57,953 - INFO - Validation time: 0.325 seconds
2023-07-26 09:20:57,954 - INFO - Execution time: 0.435 seconds
2023-07-26 09:25:44,459 - INFO - Validation time: 2.306 seconds
2023-07-26 09:25:44,476 - INFO - add_to_cart method called
2023-07-26 09:25:44,478 - INFO - checking if table exist!!...
2023-07-26 09:25:44,573 - INFO - session closed
2023-07-26 09:25:44,574 - ERROR - key error list index out of range
2023-07-26 09:25:44,575 - INFO - item not present in cart 
2023-07-26 09:25:44,576 - INFO - checking if table exist!!...
2023-07-26 09:25:44,593 - INFO - session closed
2023-07-26 09:25:44,594 - ERROR - 'bool' object is not subscriptable
2023-07-26 09:25:44,594 - INFO - Validation time: 2.321 seconds
2023-07-26 09:25:44,594 - INFO - Execution time: 2.449 seconds
2023-07-26 09:25:44,598 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-27 00:13:34,668 - INFO - Serving on http://0.0.0.0:5008
2023-07-27 00:16:23,005 - INFO - Validation time: 2.300 seconds
2023-07-27 00:16:23,029 - INFO - add_to_cart method called
2023-07-27 00:16:23,031 - INFO - checking if table exist!!...
2023-07-27 00:16:26,860 - INFO - session closed
2023-07-27 00:16:26,861 - ERROR - key error list index out of range
2023-07-27 00:16:26,861 - INFO - item not present in cart 
2023-07-27 00:16:26,861 - INFO - checking if table exist!!...
2023-07-27 00:16:27,174 - INFO - session closed
2023-07-27 00:16:27,175 - ERROR - 'bool' object is not subscriptable
2023-07-27 00:16:27,175 - INFO - Validation time: 2.315 seconds
2023-07-27 00:16:27,175 - INFO - Execution time: 6.475 seconds
2023-07-27 00:16:27,178 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-07-27 00:16:43,392 - INFO - add_to_cart method called
2023-07-27 00:16:43,393 - INFO - checking if table exist!!...
2023-07-27 00:16:45,135 - INFO - session closed
2023-07-27 00:16:45,135 - ERROR - key error list index out of range
2023-07-27 00:16:45,135 - INFO - item not present in cart 
2023-07-27 00:16:45,135 - INFO - checking if table exist!!...
2023-07-27 00:16:45,660 - INFO - session closed
2023-07-27 00:16:45,661 - INFO - checking if table exist!!...
2023-07-27 00:16:47,813 - INFO - row inserted!..
2023-07-27 00:16:48,743 - INFO - session closed
2023-07-27 00:16:48,744 - INFO - Validation time: 0.003 seconds
2023-07-27 00:16:48,744 - INFO - Execution time: 5.360 seconds
2023-07-27 00:17:01,476 - INFO - {'exp': 1690442702, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-27 00:17:01,489 - INFO - show cart  function triggered!...
2023-07-27 00:17:01,491 - INFO - checking if table exist!!...
2023-07-27 00:17:01,655 - INFO - session closed
2023-07-27 00:17:01,663 - INFO - [{'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_01', 'count': 5, 'cost': 595.0, 'net_cost': 2975.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtes899997jkjghg-jhhjghvbv86'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_01', 'count': 12, 'cost': 595.0, 'net_cost': 7140.0, 'cart_id': 'debtest56mou78012testl34ll'}, {'session_id': 'debtest56mou78012testl34ll', 'item_id': '201816_03_02', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'debtest56mou78012testl34ll'}]
2023-07-27 00:17:01,674 - INFO - Validation time: 0.003 seconds
2023-07-27 00:17:01,674 - INFO - Execution time: 0.203 seconds
2023-07-27 00:17:55,233 - INFO - Validation time: 0.167 seconds
2023-07-27 00:17:55,241 - INFO - {'exp': 1690442702, 'session_id': 'debtes899997jkjghg-jhhjghvbv86', 'user_id': 'u5AP2SioTfQaAWeKake8zOl2fdd2'}
2023-07-27 00:17:55,248 - INFO - checkout function triggered!...
2023-07-27 00:17:55,250 - INFO - checking if table exist!!...
2023-07-27 00:17:55,365 - INFO - session closed
2023-07-27 00:17:55,370 - INFO - found cart items
2023-07-27 00:17:55,376 - INFO - checking if table exist!!...
2023-07-27 00:17:55,401 - INFO - session closed
2023-07-27 00:17:55,402 - INFO - checking if table exist!!...
2023-07-27 00:17:55,412 - INFO - session closed
2023-07-27 00:17:55,413 - INFO - checking if table exist!!...
2023-07-27 00:17:55,700 - INFO - session closed
2023-07-27 00:17:55,701 - INFO - checking if table exist!!...
2023-07-27 00:17:55,708 - INFO - session closed
2023-07-27 00:17:55,708 - INFO - checkout table updated..
2023-07-27 00:17:55,709 - INFO - checking if table exist!!...
2023-07-27 00:17:55,735 - INFO - row inserted!..
2023-07-27 00:17:55,745 - INFO - session closed
2023-07-27 00:17:55,745 - INFO - {'available_order_no': '00000000-0000-0000-2eeb-5096118165ea-00', 'non_available_order_no': '00000000-0000-0000-2eeb-5096118165ea-01', 'order_id': '00000000-0000-0000-2eeb-5096118165ea', 'available': [{'item_id': '201816_03_01', 'count': 7, 'cost': 595, 'net_cost': 4165}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 11305, 'unavailable': [{'item_id': '201816_03_01', 'count': 10, 'cost': 595, 'net_cost': 5950}], 'session_id': 'debtes899997jkjghg-jhhjghvbv86'}
2023-07-27 00:17:55,746 - INFO - Validation time: 0.179 seconds
2023-07-27 00:17:55,746 - INFO - Execution time: 0.685 seconds
2023-07-28 06:45:37,384 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-07-28 06:45:37,484 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-07-28 06:45:37,486 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-07-28 06:45:37,488 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-07-28 06:45:37,490 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-08-05 09:57:18,257 - INFO - Serving on http://0.0.0.0:5008
2023-08-05 20:47:08,952 - INFO - Serving on http://0.0.0.0:5008
2023-08-05 20:51:32,126 - INFO - Validation time: 2.335 seconds
2023-08-05 20:51:32,131 - INFO - {'exp': 1691294402, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 20:51:32,135 - INFO - checkout function triggered!...
2023-08-05 20:51:32,140 - INFO - checking if table exist!!...
2023-08-05 20:51:34,525 - INFO - session closed
2023-08-05 20:51:34,527 - INFO - found cart items
2023-08-05 20:51:34,530 - INFO - checking if table exist!!...
2023-08-05 20:51:35,075 - INFO - session closed
2023-08-05 20:51:35,076 - INFO - checking if table exist!!...
2023-08-05 20:51:36,173 - INFO - session closed
2023-08-05 20:51:36,187 - INFO - checking if table exist!!...
2023-08-05 20:51:36,579 - INFO - session closed
2023-08-05 20:51:36,580 - INFO - checking if table exist!!...
2023-08-05 20:51:36,625 - INFO - session closed
2023-08-05 20:51:36,625 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-05 20:51:36,625 - INFO - checking if table exist!!...
2023-08-05 20:51:36,636 - INFO - row inserted!..
2023-08-05 20:51:36,652 - INFO - session closed
2023-08-05 20:51:36,652 - INFO - {'available_order_no': '00000000-0000-0000-2ef1-5dac2434061c-00', 'order_id': '00000000-0000-0000-2ef1-5dac2434061c', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 1785, 'unavailable': [], 'session_id': 'debtes899997jkjghg-jhhjghvbv'}
2023-08-05 20:51:36,658 - INFO - Validation time: 2.342 seconds
2023-08-05 20:51:36,658 - INFO - Execution time: 6.869 seconds
2023-08-05 20:52:30,425 - INFO - {'exp': 1691294402, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 20:52:30,433 - INFO - show cart  function triggered!...
2023-08-05 20:52:30,435 - INFO - checking if table exist!!...
2023-08-05 20:52:30,483 - INFO - session closed
2023-08-05 20:52:30,485 - INFO - [{'session_id': 'yohonesuinb#44523', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'yohonesuinb#44523'}, {'session_id': 'yohonesuinb#44523', 'item_id': '201816_03_02', 'count': 2, 'cost': 595.0, 'net_cost': 1190.0, 'cart_id': 'yohonesuinb#44523'}]
2023-08-05 20:52:30,489 - INFO - Validation time: 0.002 seconds
2023-08-05 20:52:30,489 - INFO - Execution time: 0.067 seconds
2023-08-05 20:57:20,021 - INFO - Validation time: 2.229 seconds
2023-08-05 20:57:20,023 - INFO - {'exp': 1691294402, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 20:57:20,025 - INFO - checkout function triggered!...
2023-08-05 20:57:20,025 - INFO - checking if table exist!!...
2023-08-05 20:57:20,071 - INFO - session closed
2023-08-05 20:57:20,072 - INFO - found cart items
2023-08-05 20:57:20,073 - INFO - checking if table exist!!...
2023-08-05 20:57:20,086 - INFO - session closed
2023-08-05 20:57:20,086 - INFO - checking if table exist!!...
2023-08-05 20:57:20,098 - INFO - session closed
2023-08-05 20:57:20,098 - INFO - checking if table exist!!...
2023-08-05 20:57:20,110 - INFO - session closed
2023-08-05 20:57:20,111 - INFO - checking if table exist!!...
2023-08-05 20:57:20,122 - INFO - session closed
2023-08-05 20:57:20,123 - INFO - checkout table updated..
2023-08-05 20:57:20,124 - INFO - checking if table exist!!...
2023-08-05 20:57:20,131 - ERROR - issue with query:update_checkout() missing 1 required positional argument: 'status'
2023-08-05 20:57:20,134 - INFO - session closed
2023-08-05 20:57:20,134 - INFO - None
2023-08-05 20:57:20,135 - INFO - Validation time: 2.235 seconds
2023-08-05 20:57:20,135 - INFO - Execution time: 2.347 seconds
2023-08-05 20:58:19,205 - INFO - {'exp': 1691294402, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 20:58:19,206 - INFO - show cart  function triggered!...
2023-08-05 20:58:19,206 - INFO - checking if table exist!!...
2023-08-05 20:58:19,885 - INFO - session closed
2023-08-05 20:58:19,885 - INFO - [{'session_id': 'yohonesuinb#44523', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'yohonesuinb#44523'}, {'session_id': 'yohonesuinb#44523', 'item_id': '201816_03_02', 'count': 2, 'cost': 595.0, 'net_cost': 1190.0, 'cart_id': 'yohonesuinb#44523'}]
2023-08-05 20:58:19,886 - INFO - Validation time: 0.000 seconds
2023-08-05 20:58:19,886 - INFO - Execution time: 0.682 seconds
2023-08-05 20:58:44,176 - INFO - Validation time: 0.031 seconds
2023-08-05 20:58:44,177 - INFO - {'exp': 1691294402, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 20:58:44,177 - INFO - checkout function triggered!...
2023-08-05 20:58:44,177 - INFO - checking if table exist!!...
2023-08-05 20:58:44,216 - INFO - session closed
2023-08-05 20:58:44,216 - INFO - found cart items
2023-08-05 20:58:44,217 - INFO - checking if table exist!!...
2023-08-05 20:58:44,232 - INFO - session closed
2023-08-05 20:58:44,232 - INFO - checking if table exist!!...
2023-08-05 20:58:44,248 - INFO - session closed
2023-08-05 20:58:44,248 - INFO - checking if table exist!!...
2023-08-05 20:58:44,263 - INFO - session closed
2023-08-05 20:58:44,263 - INFO - checking if table exist!!...
2023-08-05 20:58:44,930 - INFO - session closed
2023-08-05 20:58:44,930 - INFO - checkout table updated..
2023-08-05 20:58:44,930 - INFO - checking if table exist!!...
2023-08-05 20:58:44,945 - ERROR - issue with query:update_checkout() missing 1 required positional argument: 'status'
2023-08-05 20:58:44,958 - INFO - session closed
2023-08-05 20:58:44,958 - INFO - None
2023-08-05 20:58:44,959 - INFO - Validation time: 0.032 seconds
2023-08-05 20:58:44,959 - INFO - Execution time: 0.813 seconds
2023-08-05 21:06:38,256 - INFO - Serving on http://0.0.0.0:5008
2023-08-05 21:06:45,575 - INFO - Validation time: 2.215 seconds
2023-08-05 21:07:52,665 - INFO - Validation time: 0.293 seconds
2023-08-05 21:07:52,673 - INFO - {'exp': 1691295423, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:07:52,694 - INFO - checkout function triggered!...
2023-08-05 21:07:52,698 - INFO - checking if table exist!!...
2023-08-05 21:07:53,356 - INFO - session closed
2023-08-05 21:07:53,359 - INFO - found cart items
2023-08-05 21:07:53,362 - INFO - checking if table exist!!...
2023-08-05 21:07:53,403 - INFO - session closed
2023-08-05 21:07:53,403 - INFO - checking if table exist!!...
2023-08-05 21:07:53,450 - INFO - session closed
2023-08-05 21:07:53,451 - INFO - checking if table exist!!...
2023-08-05 21:07:53,487 - INFO - session closed
2023-08-05 21:07:53,487 - INFO - checking if table exist!!...
2023-08-05 21:07:53,499 - INFO - session closed
2023-08-05 21:07:53,499 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-05 21:07:53,499 - INFO - checking if table exist!!...
2023-08-05 21:07:53,517 - ERROR - issue with query:(pymysql.err.IntegrityError) (1062, "Duplicate entry '36141bb3a7ccccb7c733e7bff6b697abe84da8c6-debtes899997jkjghg-jhhj' for key 'tbl_checkout.PRIMARY'")
[SQL: INSERT INTO external.

 VALUES ('36141bb3a7ccccb7c733e7bff6b697abe84da8c6', 'debtes899997jkjghg-jhhjghvbv', '{"available_order_no": "00000000-0000-0000-2ef1-5f73f223f40c-00", "order_id": "00000000-0000-0000-2ef1-5f73f223f40c", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}], "net_total": 1785, "unavailable": [], "session_id": "debtes899997jkjghg-jhhjghvbv"}', '[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}]', 1691294873451540200, 0);]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-08-05 21:07:53,518 - INFO - session closed
2023-08-05 21:07:53,518 - INFO - None
2023-08-05 21:07:53,521 - INFO - Validation time: 0.300 seconds
2023-08-05 21:07:53,522 - INFO - Execution time: 1.149 seconds
2023-08-05 21:08:14,726 - INFO - {'exp': 1691295423, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:08:14,749 - INFO - show cart  function triggered!...
2023-08-05 21:08:14,752 - INFO - checking if table exist!!...
2023-08-05 21:08:14,825 - INFO - session closed
2023-08-05 21:08:14,827 - INFO - [{'session_id': 'yohonesuinb#44523', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'yohonesuinb#44523'}, {'session_id': 'yohonesuinb#44523', 'item_id': '201816_03_02', 'count': 2, 'cost': 595.0, 'net_cost': 1190.0, 'cart_id': 'yohonesuinb#44523'}]
2023-08-05 21:08:14,835 - INFO - Validation time: 0.006 seconds
2023-08-05 21:08:14,836 - INFO - Execution time: 0.123 seconds
2023-08-05 21:19:54,813 - INFO - Serving on http://0.0.0.0:5008
2023-08-05 21:20:15,056 - INFO - Validation time: 2.350 seconds
2023-08-05 21:22:26,970 - INFO - Validation time: 2.343 seconds
2023-08-05 21:22:26,985 - INFO - {'exp': 1691296232, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:22:27,011 - INFO - checkout function triggered!...
2023-08-05 21:22:27,015 - INFO - checking if table exist!!...
2023-08-05 21:22:27,953 - INFO - session closed
2023-08-05 21:22:27,955 - INFO - found cart items
2023-08-05 21:22:27,962 - INFO - checking if table exist!!...
2023-08-05 21:22:28,013 - INFO - session closed
2023-08-05 21:22:28,013 - INFO - checking if table exist!!...
2023-08-05 21:22:28,063 - INFO - session closed
2023-08-05 21:22:28,068 - INFO - checking if table exist!!...
2023-08-05 21:22:28,095 - INFO - session closed
2023-08-05 21:22:28,096 - INFO - here it comes
2023-08-05 21:22:28,096 - INFO - checking if table exist!!...
2023-08-05 21:22:28,111 - INFO - session closed
2023-08-05 21:22:28,111 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-05 21:22:28,112 - INFO - checking if table exist!!...
2023-08-05 21:22:28,140 - ERROR - issue with query:(pymysql.err.IntegrityError) (1062, "Duplicate entry '36141bb3a7ccccb7c733e7bff6b697abe84da8c6-debtes899997jkjghg-jhhj' for key 'tbl_checkout.PRIMARY'")
[SQL: INSERT INTO external.tbl_checkout VALUES ('36141bb3a7ccccb7c733e7bff6b697abe84da8c6', 'debtes899997jkjghg-jhhjghvbv', '{"available_order_no": "00000000-0000-0000-2ef1-610b36101e1f-00", "order_id": "00000000-0000-0000-2ef1-610b36101e1f", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}], "net_total": 1785, "unavailable": [], "session_id": "debtes899997jkjghg-jhhjghvbv"}', '[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}]', 1691295748067553100, 0);]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-08-05 21:22:28,142 - INFO - session closed
2023-08-05 21:22:28,142 - INFO - None
2023-08-05 21:22:28,147 - INFO - Validation time: 2.363 seconds
2023-08-05 21:22:28,147 - INFO - Execution time: 3.526 seconds
2023-08-05 21:35:11,525 - INFO - Validation time: 2.340 seconds
2023-08-05 21:37:26,274 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-08-05 21:37:26,328 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-08-05 21:37:28,597 - INFO - Validation time: 2.373 seconds
2023-08-05 21:37:28,604 - INFO - {'exp': 1691297183, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:37:28,618 - INFO - checkout function triggered!...
2023-08-05 21:37:28,618 - INFO - checking if table exist!!...
2023-08-05 21:37:28,626 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-08-05 21:37:28,645 - ERROR - Error: connection issue (pymysql.err.OperationalError) (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
[SQL: DESCRIBE `external`.`tbl_cart`]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-08-05 21:37:29,764 - INFO - session closed
2023-08-05 21:37:29,765 - INFO - found cart items
2023-08-05 21:37:29,769 - INFO - checking if table exist!!...
2023-08-05 21:37:29,819 - INFO - session closed
2023-08-05 21:37:29,819 - INFO - checking if table exist!!...
2023-08-05 21:37:29,838 - INFO - session closed
2023-08-05 21:37:29,839 - INFO - checking if table exist!!...
2023-08-05 21:37:29,939 - INFO - session closed
2023-08-05 21:37:29,939 - INFO - here it comes
2023-08-05 21:37:29,939 - INFO - checking if table exist!!...
2023-08-05 21:37:29,958 - INFO - session closed
2023-08-05 21:37:29,958 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-05 21:37:29,958 - INFO - checking if table exist!!...
2023-08-05 21:37:29,977 - INFO - row inserted!..
2023-08-05 21:37:29,992 - INFO - session closed
2023-08-05 21:37:29,993 - INFO - {'available_order_no': '00000000-0000-0000-2ef1-62af264be724-00', 'order_id': '00000000-0000-0000-2ef1-62af264be724', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 1785, 'unavailable': [], 'session_id': 'debtes899997jkjghg-jhhjghvbv'}
2023-08-05 21:37:29,995 - INFO - Validation time: 2.382 seconds
2023-08-05 21:37:29,995 - INFO - Execution time: 3.774 seconds
2023-08-05 21:40:53,072 - INFO - Validation time: 2.223 seconds
2023-08-05 21:40:53,076 - INFO - {'exp': 1691297183, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:40:53,078 - INFO - checkout function triggered!...
2023-08-05 21:40:53,079 - INFO - checking if table exist!!...
2023-08-05 21:40:53,131 - INFO - session closed
2023-08-05 21:40:53,133 - INFO - found cart items
2023-08-05 21:40:53,136 - INFO - checking if table exist!!...
2023-08-05 21:40:53,152 - INFO - session closed
2023-08-05 21:40:53,153 - INFO - checking if table exist!!...
2023-08-05 21:40:53,527 - INFO - session closed
2023-08-05 21:40:53,528 - INFO - checking if table exist!!...
2023-08-05 21:40:53,559 - INFO - session closed
2023-08-05 21:40:53,559 - INFO - here it comes
2023-08-05 21:40:53,559 - INFO - checking if table exist!!...
2023-08-05 21:40:53,572 - INFO - session closed
2023-08-05 21:40:53,572 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-05 21:40:53,572 - INFO - checking if table exist!!...
2023-08-05 21:40:53,584 - INFO - row inserted!..
2023-08-05 21:40:53,598 - INFO - session closed
2023-08-05 21:40:53,598 - INFO - {'available_order_no': '00000000-0000-0000-2ef1-630dd993ac1d-00', 'order_id': '00000000-0000-0000-2ef1-630dd993ac1d', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 1785, 'unavailable': [], 'session_id': 'debtes899997jkjghg-jhhjghvbv'}
2023-08-05 21:40:53,599 - INFO - Validation time: 2.232 seconds
2023-08-05 21:40:53,599 - INFO - Execution time: 2.754 seconds
2023-08-05 21:41:26,843 - INFO - {'exp': 1691297183, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:41:26,865 - INFO - checkout function triggered!...
2023-08-05 21:41:26,866 - INFO - checking if table exist!!...
2023-08-05 21:41:26,938 - INFO - session closed
2023-08-05 21:41:26,940 - INFO - found cart items
2023-08-05 21:41:26,943 - INFO - checking if table exist!!...
2023-08-05 21:41:26,965 - INFO - session closed
2023-08-05 21:41:26,965 - INFO - checking if table exist!!...
2023-08-05 21:41:27,021 - INFO - session closed
2023-08-05 21:41:27,022 - INFO - checking if table exist!!...
2023-08-05 21:41:27,073 - INFO - session closed
2023-08-05 21:41:27,073 - INFO - here it comes
2023-08-05 21:41:27,074 - INFO - checking if table exist!!...
2023-08-05 21:41:27,093 - INFO - session closed
2023-08-05 21:41:27,093 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-05 21:41:27,094 - INFO - checking if table exist!!...
2023-08-05 21:41:27,110 - INFO - row inserted!..
2023-08-05 21:41:27,135 - INFO - session closed
2023-08-05 21:41:27,136 - INFO - {'available_order_no': '00000000-0000-0000-2ef1-631d97aa55d2-00', 'order_id': '00000000-0000-0000-2ef1-631d97aa55d2', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 1785, 'unavailable': [], 'session_id': 'debtes899997jkjghg-jhhjghvbv'}
2023-08-05 21:41:27,140 - INFO - Validation time: 0.004 seconds
2023-08-05 21:41:27,140 - INFO - Execution time: 0.305 seconds
2023-08-05 21:50:45,535 - INFO - Serving on http://0.0.0.0:5008
2023-08-05 21:50:54,244 - INFO - Validation time: 3.029 seconds
2023-08-05 21:52:20,711 - INFO - Validation time: 0.253 seconds
2023-08-05 21:52:20,719 - INFO - {'exp': 1691298077, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:52:20,742 - INFO - checkout function triggered!...
2023-08-05 21:52:20,746 - INFO - checking if table exist!!...
2023-08-05 21:52:20,990 - INFO - session closed
2023-08-05 21:52:20,992 - INFO - found cart items
2023-08-05 21:52:20,994 - INFO - checking if table exist!!...
2023-08-05 21:52:21,036 - INFO - session closed
2023-08-05 21:52:21,036 - INFO - checking if table exist!!...
2023-08-05 21:52:21,091 - INFO - session closed
2023-08-05 21:52:21,095 - INFO - checking if table exist!!...
2023-08-05 21:52:21,146 - INFO - session closed
2023-08-05 21:52:21,146 - INFO - here it comes
2023-08-05 21:52:21,147 - INFO - checking if table exist!!...
2023-08-05 21:52:21,163 - INFO - session closed
2023-08-05 21:52:21,164 - INFO - checkout table updated..
2023-08-05 21:52:21,164 - INFO - checking if table exist!!...
2023-08-05 21:52:21,184 - ERROR - issue with query:Error!...no row affected
2023-08-05 21:52:21,185 - INFO - session closed
2023-08-05 21:52:21,186 - INFO - None
2023-08-05 21:52:21,189 - INFO - Validation time: 0.263 seconds
2023-08-05 21:52:21,189 - INFO - Execution time: 0.734 seconds
2023-08-05 21:57:15,780 - INFO - Serving on http://0.0.0.0:5008
2023-08-05 21:57:23,253 - INFO - Validation time: 2.272 seconds
2023-08-05 21:57:23,254 - INFO - {'exp': 1691298077, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:57:23,255 - INFO - checkout function triggered!...
2023-08-05 21:57:23,255 - INFO - checking if table exist!!...
2023-08-05 21:57:23,364 - INFO - session closed
2023-08-05 21:57:23,365 - INFO - found cart items
2023-08-05 21:57:23,366 - INFO - checking if table exist!!...
2023-08-05 21:57:23,387 - INFO - session closed
2023-08-05 21:57:23,387 - INFO - checking if table exist!!...
2023-08-05 21:57:23,423 - INFO - session closed
2023-08-05 21:57:23,424 - INFO - checking if table exist!!...
2023-08-05 21:57:23,455 - INFO - session closed
2023-08-05 21:57:23,455 - INFO - here it comes
2023-08-05 21:57:23,456 - INFO - checking if table exist!!...
2023-08-05 21:57:23,500 - INFO - session closed
2023-08-05 21:57:23,500 - INFO - checkout table updated..
2023-08-05 21:57:23,500 - INFO - checking if table exist!!...
2023-08-05 21:57:23,508 - INFO - Update external.tbl_checkout SET checkout_details='{"available_order_no": "00000000-0000-0000-2ef1-64daf65661dc-00", "order_id": "00000000-0000-0000-2ef1-64daf65661dc", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}], "net_total": 1785, "unavailable": [], "session_id": "debtes899997jkjghg-jhhjghvbv"}', ldts='1691297843424457100', full_order='[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}]' where uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='debtes899997jkjghg-jhhjghvbv and status=0';
2023-08-05 21:57:23,518 - ERROR - issue with query:Error!...no row affected
2023-08-05 21:57:23,518 - INFO - session closed
2023-08-05 21:57:23,518 - INFO - None
2023-08-05 21:57:23,519 - INFO - Validation time: 2.273 seconds
2023-08-05 21:57:23,519 - INFO - Execution time: 2.539 seconds
2023-08-05 21:58:22,161 - INFO - Serving on http://0.0.0.0:5008
2023-08-05 21:58:29,769 - INFO - Validation time: 2.217 seconds
2023-08-05 21:58:29,770 - INFO - {'exp': 1691298077, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 21:58:29,770 - INFO - checkout function triggered!...
2023-08-05 21:58:29,770 - INFO - checking if table exist!!...
2023-08-05 21:58:29,856 - INFO - session closed
2023-08-05 21:58:29,856 - INFO - found cart items
2023-08-05 21:58:29,857 - INFO - checking if table exist!!...
2023-08-05 21:58:29,875 - INFO - session closed
2023-08-05 21:58:29,876 - INFO - checking if table exist!!...
2023-08-05 21:58:29,915 - INFO - session closed
2023-08-05 21:58:29,916 - INFO - checking if table exist!!...
2023-08-05 21:58:29,965 - INFO - session closed
2023-08-05 21:58:29,966 - INFO - here it comes
2023-08-05 21:58:29,966 - INFO - checking if table exist!!...
2023-08-05 21:58:30,029 - INFO - session closed
2023-08-05 21:58:30,029 - INFO - checkout table updated..
2023-08-05 21:58:30,029 - INFO - checking if table exist!!...
2023-08-05 21:58:30,039 - INFO - Update external.tbl_checkout SET checkout_details='{"available_order_no": "00000000-0000-0000-2ef1-64f9ecc5bea1-00", "order_id": "00000000-0000-0000-2ef1-64f9ecc5bea1", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}], "net_total": 1785, "unavailable": [], "session_id": "debtes899997jkjghg-jhhjghvbv"}', ldts='1691297909916971200', full_order='[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}]' where uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='debtes899997jkjghg-jhhjghvbv' and status=0;
2023-08-05 21:58:30,060 - ERROR - issue with query:(pymysql.err.IntegrityError) (1062, "Duplicate entry '36141bb3a7ccccb7c733e7bff6b697abe84da8c6-debtes899997jkjghg-jhhj' for key 'tbl_checkout.PRIMARY'")
[SQL: Update external.tbl_checkout SET checkout_details='{"available_order_no": "00000000-0000-0000-2ef1-64f9ecc5bea1-00", "order_id": "00000000-0000-0000-2ef1-64f9ecc5bea1", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}], "net_total": 1785, "unavailable": [], "session_id": "debtes899997jkjghg-jhhjghvbv"}', ldts='1691297909916971200', full_order='[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}]' where uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='debtes899997jkjghg-jhhjghvbv' and status=0;]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-08-05 21:58:30,060 - INFO - session closed
2023-08-05 21:58:30,061 - INFO - None
2023-08-05 21:58:30,061 - INFO - Validation time: 2.218 seconds
2023-08-05 21:58:30,061 - INFO - Execution time: 2.509 seconds
2023-08-05 22:22:17,083 - INFO - Validation time: 2.223 seconds
2023-08-05 22:22:17,088 - INFO - {'exp': 1691299876, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 22:22:17,092 - INFO - checkout function triggered!...
2023-08-05 22:22:17,092 - INFO - checking if table exist!!...
2023-08-05 22:22:17,105 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-08-05 22:22:17,277 - ERROR - Error: connection issue (pymysql.err.OperationalError) (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
[SQL: DESCRIBE `external`.`tbl_cart`]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-08-05 22:22:18,440 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\event\base.py", line 147, in __init__
    self._empty_listeners = self._empty_listener_reg[instance_cls]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\weakref.py", line 396, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x000001C0DED1E1D8; to 'type' at 0x000001C0DEA550F8 (Session)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 760, in _write_bytes
    self._sock.sendall(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 995, in _finalize_fairy
    asyncio_safe=can_manipulate_connection,
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\pool\base.py", line 1440, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sqlalchemy\engine\default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 481, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 818, in _execute_command
    self._write_bytes(packet)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pymysql\connections.py", line 764, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))")
2023-08-05 22:22:18,493 - INFO - session closed
2023-08-05 22:22:18,493 - INFO - found cart items
2023-08-05 22:22:18,496 - INFO - checking if table exist!!...
2023-08-05 22:22:18,554 - INFO - session closed
2023-08-05 22:22:18,554 - INFO - checking if table exist!!...
2023-08-05 22:22:18,563 - INFO - session closed
2023-08-05 22:22:18,563 - INFO - checking if table exist!!...
2023-08-05 22:22:18,573 - INFO - session closed
2023-08-05 22:22:18,574 - INFO - here it comes
2023-08-05 22:22:18,574 - INFO - checking if table exist!!...
2023-08-05 22:22:18,583 - INFO - session closed
2023-08-05 22:22:18,584 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-05 22:22:18,584 - INFO - checking if table exist!!...
2023-08-05 22:22:18,600 - INFO - row inserted!..
2023-08-05 22:22:18,609 - INFO - session closed
2023-08-05 22:22:18,609 - INFO - {'available_order_no': '00000000-0000-0000-2ef1-67932f82feb3-00', 'order_id': '00000000-0000-0000-2ef1-67932f82feb3', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 1785, 'unavailable': [], 'session_id': 'debtes899997jkjghg-jhhjghvbv'}
2023-08-05 22:22:18,610 - INFO - Validation time: 2.233 seconds
2023-08-05 22:22:18,610 - INFO - Execution time: 3.755 seconds
2023-08-05 22:25:18,714 - INFO - Validation time: 2.325 seconds
2023-08-05 22:25:18,715 - INFO - {'exp': 1691299876, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 22:25:18,717 - INFO - checkout function triggered!...
2023-08-05 22:25:18,717 - INFO - checking if table exist!!...
2023-08-05 22:25:18,739 - INFO - session closed
2023-08-05 22:25:18,740 - INFO - found cart items
2023-08-05 22:25:18,741 - INFO - checking if table exist!!...
2023-08-05 22:25:18,748 - INFO - session closed
2023-08-05 22:25:18,748 - INFO - checking if table exist!!...
2023-08-05 22:25:18,755 - INFO - session closed
2023-08-05 22:25:18,756 - INFO - checking if table exist!!...
2023-08-05 22:25:18,763 - INFO - session closed
2023-08-05 22:25:18,763 - INFO - here it comes
2023-08-05 22:25:18,763 - INFO - checking if table exist!!...
2023-08-05 22:25:18,787 - INFO - session closed
2023-08-05 22:25:18,787 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-05 22:25:18,787 - INFO - checking if table exist!!...
2023-08-05 22:25:18,828 - INFO - row inserted!..
2023-08-05 22:25:18,839 - INFO - session closed
2023-08-05 22:25:18,839 - INFO - {'available_order_no': '00000000-0000-0000-2ef1-67e71e9dbb4b-00', 'order_id': '00000000-0000-0000-2ef1-67e71e9dbb4b', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 1785, 'unavailable': [], 'session_id': 'debtes899997jkjghg-jhhjghvbv'}
2023-08-05 22:25:18,841 - INFO - Validation time: 2.335 seconds
2023-08-05 22:25:18,841 - INFO - Execution time: 2.461 seconds
2023-08-05 22:25:29,567 - INFO - {'exp': 1691299876, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 22:25:29,567 - INFO - checkout function triggered!...
2023-08-05 22:25:29,567 - INFO - checking if table exist!!...
2023-08-05 22:25:29,576 - INFO - session closed
2023-08-05 22:25:29,576 - INFO - found cart items
2023-08-05 22:25:29,576 - INFO - checking if table exist!!...
2023-08-05 22:25:29,584 - INFO - session closed
2023-08-05 22:25:29,584 - INFO - checking if table exist!!...
2023-08-05 22:25:29,591 - INFO - session closed
2023-08-05 22:25:29,591 - INFO - checking if table exist!!...
2023-08-05 22:25:29,598 - INFO - session closed
2023-08-05 22:25:29,598 - INFO - here it comes
2023-08-05 22:25:29,598 - INFO - checking if table exist!!...
2023-08-05 22:25:29,632 - INFO - session closed
2023-08-05 22:25:29,632 - INFO - checkout table updated..
2023-08-05 22:25:29,632 - INFO - checking if table exist!!...
2023-08-05 22:25:29,636 - INFO - Update external.tbl_checkout SET checkout_details='{"available_order_no": "00000000-0000-0000-2ef1-67ec2a549664-00", "order_id": "00000000-0000-0000-2ef1-67ec2a549664", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}], "net_total": 1785, "unavailable": [], "session_id": "debtes899997jkjghg-jhhjghvbv"}', ldts='1691299529591036800', full_order='[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}]' where uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='debtes899997jkjghg-jhhjghvbv' and status=0;
2023-08-05 22:25:29,646 - INFO - row inserted!..
2023-08-05 22:25:29,653 - INFO - session closed
2023-08-05 22:25:29,654 - INFO - {'available_order_no': '00000000-0000-0000-2ef1-67ec2a549664-00', 'order_id': '00000000-0000-0000-2ef1-67ec2a549664', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 1785, 'unavailable': [], 'session_id': 'debtes899997jkjghg-jhhjghvbv'}
2023-08-05 22:25:29,654 - INFO - Validation time: 0.000 seconds
2023-08-05 22:25:29,654 - INFO - Execution time: 0.088 seconds
2023-08-05 22:25:42,160 - INFO - {'exp': 1691299876, 'session_id': 'debtes899997jkjghg-jhhjghvbv', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-05 22:25:42,160 - INFO - checkout function triggered!...
2023-08-05 22:25:42,160 - INFO - checking if table exist!!...
2023-08-05 22:25:42,171 - INFO - session closed
2023-08-05 22:25:42,172 - INFO - found cart items
2023-08-05 22:25:42,172 - INFO - checking if table exist!!...
2023-08-05 22:25:42,181 - INFO - session closed
2023-08-05 22:25:42,182 - INFO - checking if table exist!!...
2023-08-05 22:25:42,192 - INFO - session closed
2023-08-05 22:25:42,192 - INFO - checking if table exist!!...
2023-08-05 22:25:42,203 - INFO - session closed
2023-08-05 22:25:42,203 - INFO - here it comes
2023-08-05 22:25:42,203 - INFO - checking if table exist!!...
2023-08-05 22:25:42,245 - INFO - session closed
2023-08-05 22:25:42,245 - INFO - checkout table updated..
2023-08-05 22:25:42,245 - INFO - checking if table exist!!...
2023-08-05 22:25:42,250 - INFO - Update external.tbl_checkout SET checkout_details='{"available_order_no": "00000000-0000-0000-2ef1-67f207f31b3a-00", "order_id": "00000000-0000-0000-2ef1-67f207f31b3a", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}], "net_total": 1785, "unavailable": [], "session_id": "debtes899997jkjghg-jhhjghvbv"}', ldts='1691299542192529700', full_order='[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}, {"item_id": "201816_03_02", "count": 2, "cost": "595", "net_cost": 1190}]' where uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='debtes899997jkjghg-jhhjghvbv' and status=0;
2023-08-05 22:25:42,272 - INFO - row inserted!..
2023-08-05 22:25:42,279 - INFO - session closed
2023-08-05 22:25:42,280 - INFO - {'available_order_no': '00000000-0000-0000-2ef1-67f207f31b3a-00', 'order_id': '00000000-0000-0000-2ef1-67f207f31b3a', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}, {'item_id': '201816_03_02', 'count': 2, 'cost': '595', 'net_cost': 1190}], 'net_total': 1785, 'unavailable': [], 'session_id': 'debtes899997jkjghg-jhhjghvbv'}
2023-08-05 22:25:42,280 - INFO - Validation time: 0.001 seconds
2023-08-05 22:25:42,280 - INFO - Execution time: 0.121 seconds
2023-08-31 05:05:05,572 - INFO - Serving on http://0.0.0.0:5008
2023-08-31 05:05:14,085 - INFO - Validation time: 2.275 seconds
2023-08-31 05:06:02,146 - INFO - Validation time: 0.081 seconds
2023-08-31 05:07:48,097 - INFO - Validation time: 0.102 seconds
2023-08-31 05:07:48,105 - INFO - {'exp': 1693484237, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:07:48,124 - INFO - checkout function triggered!...
2023-08-31 05:07:48,127 - INFO - checking if table exist!!...
2023-08-31 05:07:48,307 - INFO - session closed
2023-08-31 05:07:48,308 - INFO - False
2023-08-31 05:07:48,310 - INFO - Validation time: 0.110 seconds
2023-08-31 05:07:48,310 - INFO - Execution time: 0.316 seconds
2023-08-31 05:08:15,473 - INFO - add_to_cart method called
2023-08-31 05:08:15,474 - INFO - checking if table exist!!...
2023-08-31 05:08:15,488 - INFO - session closed
2023-08-31 05:08:15,489 - ERROR - key error list index out of range
2023-08-31 05:08:15,489 - INFO - item not present in cart 
2023-08-31 05:08:15,490 - INFO - checking if table exist!!...
2023-08-31 05:08:15,680 - INFO - session closed
2023-08-31 05:08:15,680 - ERROR - 'bool' object is not subscriptable
2023-08-31 05:08:15,680 - INFO - Validation time: 0.001 seconds
2023-08-31 05:08:15,680 - INFO - Execution time: 0.213 seconds
2023-08-31 05:08:15,685 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-31 05:08:34,958 - INFO - add_to_cart method called
2023-08-31 05:08:34,960 - INFO - checking if table exist!!...
2023-08-31 05:08:34,997 - INFO - session closed
2023-08-31 05:08:34,998 - ERROR - key error list index out of range
2023-08-31 05:08:34,998 - INFO - item not present in cart 
2023-08-31 05:08:34,998 - INFO - checking if table exist!!...
2023-08-31 05:08:35,011 - INFO - session closed
2023-08-31 05:08:35,011 - ERROR - 'bool' object is not subscriptable
2023-08-31 05:08:35,012 - INFO - Validation time: 0.000 seconds
2023-08-31 05:08:35,012 - INFO - Execution time: 0.057 seconds
2023-08-31 05:08:35,012 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-31 05:19:44,702 - INFO - Validation time: 2.268 seconds
2023-08-31 05:21:11,389 - INFO - Validation time: 0.209 seconds
2023-08-31 05:21:11,404 - INFO - add_to_cart method called
2023-08-31 05:21:11,405 - INFO - checking if table exist!!...
2023-08-31 05:21:11,478 - INFO - session closed
2023-08-31 05:21:11,479 - ERROR - key error list index out of range
2023-08-31 05:21:11,479 - INFO - item not present in cart 
2023-08-31 05:21:11,479 - INFO - checking if table exist!!...
2023-08-31 05:21:11,487 - INFO - session closed
2023-08-31 05:21:11,487 - INFO - checking if table exist!!...
2023-08-31 05:21:11,544 - INFO - row inserted!..
2023-08-31 05:21:11,556 - INFO - session closed
2023-08-31 05:21:11,556 - INFO - Validation time: 0.219 seconds
2023-08-31 05:21:11,556 - INFO - Execution time: 0.380 seconds
2023-08-31 05:21:49,316 - INFO - {'exp': 1693485028, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:21:49,329 - INFO - show cart  function triggered!...
2023-08-31 05:21:49,331 - INFO - checking if table exist!!...
2023-08-31 05:21:49,372 - INFO - session closed
2023-08-31 05:21:49,376 - INFO - [{'session_id': 'ghsgdhsh7873673hwgikk', 'item_id': '201816_03_01', 'count': 1, 'cost': 595.0, 'net_cost': 595.0, 'cart_id': 'ghsgdhsh7873673hwgikk'}]
2023-08-31 05:21:49,383 - INFO - Validation time: 0.002 seconds
2023-08-31 05:21:49,383 - INFO - Execution time: 0.071 seconds
2023-08-31 05:22:39,454 - INFO - Validation time: 0.207 seconds
2023-08-31 05:22:39,460 - INFO - {'exp': 1693485028, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:22:39,462 - ERROR - 'discount_code'
2023-08-31 05:22:39,462 - INFO - Validation time: 0.219 seconds
2023-08-31 05:22:39,462 - INFO - Execution time: 0.222 seconds
2023-08-31 05:22:39,465 - ERROR - Exception on /checkout_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'checkout_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-31 05:23:29,250 - INFO - {'exp': 1693485028, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:23:29,268 - INFO - checkout function triggered!...
2023-08-31 05:23:29,270 - INFO - checking if table exist!!...
2023-08-31 05:23:29,340 - INFO - session closed
2023-08-31 05:23:29,341 - INFO - found cart items
2023-08-31 05:23:29,353 - INFO - checking if table exist!!...
2023-08-31 05:23:29,361 - INFO - session closed
2023-08-31 05:23:29,362 - INFO - checking if table exist!!...
2023-08-31 05:23:29,365 - INFO - query select discount_id,total_discount_in_prcnt,valid_from,valid_upto from external.tbl_discount where discount_id='None' or is_active=1 and valid_upto>0;
2023-08-31 05:23:29,406 - INFO - session closed
2023-08-31 05:23:29,406 - ERROR - 'valid_form'
2023-08-31 05:23:29,406 - INFO - Validation time: 0.004 seconds
2023-08-31 05:23:29,406 - INFO - Execution time: 0.163 seconds
2023-08-31 05:23:29,407 - ERROR - Exception on /checkout_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'checkout_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-31 05:24:20,062 - INFO - Validation time: 0.135 seconds
2023-08-31 05:24:20,066 - INFO - {'exp': 1693485028, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:24:20,072 - INFO - checkout function triggered!...
2023-08-31 05:24:20,072 - INFO - checking if table exist!!...
2023-08-31 05:24:20,115 - INFO - session closed
2023-08-31 05:24:20,117 - INFO - found cart items
2023-08-31 05:24:20,118 - INFO - checking if table exist!!...
2023-08-31 05:24:20,126 - INFO - session closed
2023-08-31 05:24:20,126 - INFO - checking if table exist!!...
2023-08-31 05:24:20,130 - INFO - query select discount_id,total_discount_in_prcnt,valid_from,valid_upto from external.tbl_discount where discount_id='' or is_active=1 and valid_upto>0;
2023-08-31 05:24:20,137 - INFO - session closed
2023-08-31 05:24:20,138 - ERROR - 'valid_form'
2023-08-31 05:24:20,138 - INFO - Validation time: 0.145 seconds
2023-08-31 05:24:20,138 - INFO - Execution time: 0.217 seconds
2023-08-31 05:24:20,140 - ERROR - Exception on /checkout_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'checkout_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-31 05:38:13,359 - INFO - Serving on http://0.0.0.0:5008
2023-08-31 05:38:29,287 - INFO - Validation time: 2.207 seconds
2023-08-31 05:39:17,648 - INFO - Validation time: 0.221 seconds
2023-08-31 05:39:17,655 - INFO - {'exp': 1693486124, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:39:17,670 - INFO - checkout function triggered!...
2023-08-31 05:39:17,672 - INFO - checking if table exist!!...
2023-08-31 05:39:17,843 - INFO - session closed
2023-08-31 05:39:17,844 - INFO - found cart items
2023-08-31 05:39:17,849 - INFO - checking if table exist!!...
2023-08-31 05:39:17,859 - INFO - session closed
2023-08-31 05:39:17,860 - INFO - checking if table exist!!...
2023-08-31 05:39:17,863 - INFO - query select discount_id,total_discount_in_prcnt,valid_from,valid_upto from external.tbl_discount where discount_id='' or is_active=1 and valid_upto>0;
2023-08-31 05:39:17,868 - INFO - session closed
2023-08-31 05:39:17,870 - INFO - checking if table exist!!...
2023-08-31 05:39:17,892 - INFO - session closed
2023-08-31 05:39:17,892 - INFO - here it comes
2023-08-31 05:39:17,892 - INFO - checking if table exist!!...
2023-08-31 05:39:17,905 - INFO - session closed
2023-08-31 05:39:17,905 - INFO - no record found with same uid & sessionid . Inserting...
2023-08-31 05:39:17,905 - INFO - checking if table exist!!...
2023-08-31 05:39:17,915 - INFO - row inserted!..
2023-08-31 05:39:17,925 - INFO - session closed
2023-08-31 05:39:17,925 - INFO - {'available_order_no': '00000000-0000-0000-2f00-f048e7267fa7-00', 'order_id': '00000000-0000-0000-2f00-f048e7267fa7', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}], 'net_total': 595, 'unavailable': [], 'session_id': 'ghsgdhsh7873673hwgikk', 'wt_discount_id': 'DISCOUNT001', 'wt_discount_prtn': 15, 'net_cost': 595.0, 'total': 505.75}
2023-08-31 05:39:17,930 - INFO - Validation time: 0.230 seconds
2023-08-31 05:39:17,930 - INFO - Execution time: 0.504 seconds
2023-08-31 05:41:27,880 - INFO - Validation time: 0.141 seconds
2023-08-31 05:41:27,885 - INFO - {'exp': 1693486124, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:41:27,887 - INFO - checkout function triggered!...
2023-08-31 05:41:27,888 - INFO - checking if table exist!!...
2023-08-31 05:41:27,919 - INFO - session closed
2023-08-31 05:41:27,919 - INFO - found cart items
2023-08-31 05:41:27,920 - INFO - checking if table exist!!...
2023-08-31 05:41:27,928 - INFO - session closed
2023-08-31 05:41:27,929 - INFO - checking if table exist!!...
2023-08-31 05:41:27,934 - INFO - query select discount_id,total_discount_in_prcnt,valid_from,valid_upto from external.tbl_discount where discount_id='DISCOUNT006' or is_active=1 and valid_upto>0;
2023-08-31 05:41:27,940 - INFO - session closed
2023-08-31 05:41:27,940 - INFO - checking if table exist!!...
2023-08-31 05:41:27,986 - INFO - session closed
2023-08-31 05:41:27,986 - INFO - here it comes
2023-08-31 05:41:27,986 - INFO - checking if table exist!!...
2023-08-31 05:41:28,032 - INFO - session closed
2023-08-31 05:41:28,032 - INFO - checkout table updated..
2023-08-31 05:41:28,033 - INFO - checking if table exist!!...
2023-08-31 05:41:28,036 - INFO - Update external.tbl_checkout SET checkout_details='{"available_order_no": "00000000-0000-0000-2f00-f08579565a2d-00", "order_id": "00000000-0000-0000-2f00-f08579565a2d", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}], "net_total": 595, "unavailable": [], "session_id": "ghsgdhsh7873673hwgikk", "wt_discount_id": "DISCOUNT001", "wt_discount_prtn": 15, "net_cost": 595.0, "total": 505.75}', ldts='1693485687940777900', full_order='[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}]' where uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='ghsgdhsh7873673hwgikk' and status=0;
2023-08-31 05:41:28,038 - INFO - row inserted!..
2023-08-31 05:41:28,045 - INFO - session closed
2023-08-31 05:41:28,045 - INFO - {'available_order_no': '00000000-0000-0000-2f00-f08579565a2d-00', 'order_id': '00000000-0000-0000-2f00-f08579565a2d', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}], 'net_total': 595, 'unavailable': [], 'session_id': 'ghsgdhsh7873673hwgikk', 'wt_discount_id': 'DISCOUNT001', 'wt_discount_prtn': 15, 'net_cost': 595.0, 'total': 505.75}
2023-08-31 05:41:28,047 - INFO - Validation time: 0.148 seconds
2023-08-31 05:41:28,047 - INFO - Execution time: 0.311 seconds
2023-08-31 05:47:28,616 - INFO - Serving on http://0.0.0.0:5008
2023-08-31 05:47:41,523 - INFO - Validation time: 2.218 seconds
2023-08-31 05:47:41,526 - INFO - {'exp': 1693486124, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:47:41,530 - INFO - checkout function triggered!...
2023-08-31 05:47:41,531 - INFO - checking if table exist!!...
2023-08-31 05:47:42,327 - INFO - session closed
2023-08-31 05:47:42,329 - INFO - found cart items
2023-08-31 05:47:42,330 - INFO - checking if table exist!!...
2023-08-31 05:47:42,740 - INFO - session closed
2023-08-31 05:47:42,741 - INFO - checking if table exist!!...
2023-08-31 05:47:42,747 - INFO - query select discount_id,total_discount_in_prcnt,valid_from,valid_upto from external.tbl_discount where discount_id='DISCOUNT006' or is_active=1 and valid_upto>0;
2023-08-31 05:47:42,758 - INFO - session closed
2023-08-31 05:47:42,760 - INFO - checking if table exist!!...
2023-08-31 05:47:42,771 - INFO - session closed
2023-08-31 05:47:42,772 - INFO - here it comes
2023-08-31 05:47:42,772 - INFO - checking if table exist!!...
2023-08-31 05:47:42,782 - INFO - session closed
2023-08-31 05:47:42,782 - INFO - checkout table updated..
2023-08-31 05:47:42,782 - INFO - checking if table exist!!...
2023-08-31 05:47:42,787 - INFO - Update external.tbl_checkout SET checkout_details='{"available_order_no": "00000000-0000-0000-2f00-f133d2729281-00", "order_id": "00000000-0000-0000-2f00-f133d2729281", "available": [{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}], "net_total": 595, "unavailable": [], "session_id": "ghsgdhsh7873673hwgikk", "vendor_discount_id": "DISCOUNT006", "vendor_discount_pctn": 5, "wt_discount_id": "DISCOUNT001", "wt_discount_prtn": 15, "net_cost": 565.25, "total": 480.4625}', ldts='1693486062760206100', full_order='[{"item_id": "201816_03_01", "count": 1, "cost": "595", "net_cost": 595}]' where uid='36141bb3a7ccccb7c733e7bff6b697abe84da8c6'and session_id='ghsgdhsh7873673hwgikk' and status=0;
2023-08-31 05:47:42,798 - INFO - row inserted!..
2023-08-31 05:47:42,812 - INFO - session closed
2023-08-31 05:47:42,812 - INFO - {'available_order_no': '00000000-0000-0000-2f00-f133d2729281-00', 'order_id': '00000000-0000-0000-2f00-f133d2729281', 'available': [{'item_id': '201816_03_01', 'count': 1, 'cost': '595', 'net_cost': 595}], 'net_total': 595, 'unavailable': [], 'session_id': 'ghsgdhsh7873673hwgikk', 'vendor_discount_id': 'DISCOUNT006', 'vendor_discount_pctn': 5, 'wt_discount_id': 'DISCOUNT001', 'wt_discount_prtn': 15, 'net_cost': 565.25, 'total': 480.4625}
2023-08-31 05:47:42,817 - INFO - Validation time: 2.223 seconds
2023-08-31 05:47:42,817 - INFO - Execution time: 3.514 seconds
2023-08-31 05:53:43,496 - INFO - Validation time: 2.854 seconds
2023-08-31 05:54:39,592 - INFO - Validation time: 0.133 seconds
2023-08-31 05:54:39,605 - INFO - add_to_cart method called
2023-08-31 05:54:39,607 - INFO - checking if table exist!!...
2023-08-31 05:54:39,694 - INFO - session closed
2023-08-31 05:54:39,695 - INFO - item is already present in cart!! updating..
2023-08-31 05:54:39,696 - INFO - checking if table exist!!...
2023-08-31 05:54:39,707 - INFO - session closed
2023-08-31 05:54:39,708 - INFO - checking if table exist!!...
2023-08-31 05:54:39,716 - INFO - row inserted!..
2023-08-31 05:54:39,723 - INFO - session closed
2023-08-31 05:54:39,723 - INFO - Validation time: 0.140 seconds
2023-08-31 05:54:39,723 - INFO - Execution time: 0.268 seconds
2023-08-31 05:55:09,296 - INFO - {'exp': 1693487039, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 05:55:09,299 - INFO - show cart  function triggered!...
2023-08-31 05:55:09,300 - INFO - checking if table exist!!...
2023-08-31 05:55:09,347 - INFO - session closed
2023-08-31 05:55:09,350 - INFO - [{'session_id': 'ghsgdhsh7873673hwgikk', 'item_id': '201816_03_01', 'count': 2, 'cost': 595.0, 'net_cost': 1190.0, 'cart_id': 'ghsgdhsh7873673hwgikk'}]
2023-08-31 05:55:09,354 - INFO - Validation time: 0.000 seconds
2023-08-31 05:55:09,354 - INFO - Execution time: 0.059 seconds
2023-08-31 06:41:29,619 - INFO - Validation time: 2.609 seconds
2023-08-31 06:41:29,631 - INFO - {'exp': 1693489773, 'session_id': 'ghsgdhsh7873673hwgikk', 'user_id': 'ycmdefme9qg8BSRMSPqV1pKZfH93'}
2023-08-31 06:41:29,639 - INFO - show cart  function triggered!...
2023-08-31 06:41:29,642 - INFO - checking if table exist!!...
2023-08-31 06:41:29,743 - INFO - session closed
2023-08-31 06:41:29,744 - INFO - []
2023-08-31 06:41:29,761 - INFO - Validation time: 2.626 seconds
2023-08-31 06:41:29,761 - INFO - Execution time: 2.756 seconds
2023-08-31 06:41:56,422 - INFO - add_to_cart method called
2023-08-31 06:41:56,430 - INFO - checking if table exist!!...
2023-08-31 06:41:56,503 - INFO - session closed
2023-08-31 06:41:56,505 - INFO - item is already present in cart!! updating..
2023-08-31 06:41:56,506 - INFO - checking if table exist!!...
2023-08-31 06:41:56,521 - INFO - session closed
2023-08-31 06:41:56,522 - INFO - checking if table exist!!...
2023-08-31 06:41:56,541 - INFO - row inserted!..
2023-08-31 06:41:56,558 - INFO - session closed
2023-08-31 06:41:56,558 - INFO - Validation time: 0.004 seconds
2023-08-31 06:41:56,559 - INFO - Execution time: 0.157 seconds
2023-08-31 06:48:56,214 - INFO - Serving on http://0.0.0.0:5008
2023-08-31 06:49:28,937 - INFO - Validation time: 2.505 seconds
2023-08-31 06:49:28,952 - INFO - add_to_cart method called
2023-08-31 06:49:28,953 - INFO - checking if table exist!!...
2023-08-31 06:49:29,098 - INFO - session closed
2023-08-31 06:49:29,099 - ERROR - key error list index out of range
2023-08-31 06:49:29,099 - INFO - item not present in cart 
2023-08-31 06:49:29,100 - INFO - checking if table exist!!...
2023-08-31 06:49:29,137 - INFO - session closed
2023-08-31 06:49:29,137 - INFO - checking if table exist!!...
2023-08-31 06:49:29,148 - INFO - row inserted!..
2023-08-31 06:49:29,162 - INFO - session closed
2023-08-31 06:49:29,162 - INFO - Validation time: 2.517 seconds
2023-08-31 06:49:29,162 - INFO - Execution time: 2.737 seconds
2023-08-31 06:50:12,361 - INFO - add_to_cart method called
2023-08-31 06:50:12,362 - INFO - checking if table exist!!...
2023-08-31 06:50:12,385 - INFO - session closed
2023-08-31 06:50:12,385 - INFO - item is already present in cart!! updating..
2023-08-31 06:50:12,385 - INFO - checking if table exist!!...
2023-08-31 06:50:12,433 - INFO - session closed
2023-08-31 06:50:12,434 - INFO - checking if table exist!!...
2023-08-31 06:50:12,511 - ERROR - issue with query:(pymysql.err.IntegrityError) (1062, "Duplicate entry 'ghsgdhsh7873673hwgikk-201816_03_01-1' for key 'tbl_cart.PRIMARY'")
[SQL: Update external.tbl_cart SET count=2, is_active=1, net_cost=2*595 where item_id='201816_03_01'and session_id='ghsgdhsh7873673hwgikk';]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-08-31 06:50:12,512 - INFO - session closed
2023-08-31 06:50:12,512 - ERROR - No response found. Internal Error.
2023-08-31 06:50:12,512 - INFO - Validation time: 0.001 seconds
2023-08-31 06:50:12,512 - INFO - Execution time: 0.157 seconds
2023-08-31 06:50:12,516 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-31 06:50:46,869 - INFO - Validation time: 0.256 seconds
2023-08-31 06:51:54,093 - INFO - Validation time: 0.295 seconds
2023-08-31 06:51:54,110 - INFO - add_to_cart method called
2023-08-31 06:51:54,113 - INFO - checking if table exist!!...
2023-08-31 06:51:54,198 - INFO - session closed
2023-08-31 06:51:54,199 - INFO - item is already present in cart!! updating..
2023-08-31 06:51:54,199 - INFO - checking if table exist!!...
2023-08-31 06:51:54,213 - INFO - session closed
2023-08-31 06:51:54,213 - INFO - checking if table exist!!...
2023-08-31 06:51:54,232 - ERROR - issue with query:(pymysql.err.IntegrityError) (1062, "Duplicate entry 'ghsgdhsh7873673hwgikk-201816_03_01-1' for key 'tbl_cart.PRIMARY'")
[SQL: Update external.tbl_cart SET count=2, is_active=1, net_cost=2*595 where item_id='201816_03_01'and session_id='ghsgdhsh7873673hwgikk';]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-08-31 06:51:54,234 - INFO - session closed
2023-08-31 06:51:54,234 - ERROR - No response found. Internal Error.
2023-08-31 06:51:54,234 - INFO - Validation time: 0.305 seconds
2023-08-31 06:51:54,234 - INFO - Execution time: 0.439 seconds
2023-08-31 06:51:54,235 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
